#pragma once
#ifdef GAME_HPP
#include "bg.hpp"              // IWYU pragma: export
#include "cbuf.hpp"            // IWYU pragma: export
#include "cg.hpp"              // IWYU pragma: export
#include "cinematic.hpp"       // IWYU pragma: export
#include "cl.hpp"              // IWYU pragma: export
#include "cmd.hpp"             // IWYU pragma: export
#include "com.hpp"             // IWYU pragma: export
#include "con.hpp"             // IWYU pragma: export
#include "db/core.hpp"         // IWYU pragma: export
#include "db/db.hpp"           // IWYU pragma: export
#include "db/load.hpp"         // IWYU pragma: export
#include "db/xasset.hpp"       // IWYU pragma: export
#include "db/xzone.hpp"        // IWYU pragma: export
#include "dvar.hpp"            // IWYU pragma: export
#include "fs.hpp"              // IWYU pragma: export
#include "game.hpp"            // IWYU pragma: export
#include "glasssv.hpp"         // IWYU pragma: export
#include "info.hpp"            // IWYU pragma: export
#include "jq.hpp"              // IWYU pragma: export
#include "level.hpp"           // IWYU pragma: export
#include "live/live.hpp"       // IWYU pragma: export
#include "lobby.hpp"           // IWYU pragma: export
#include "macros.hpp"          // IWYU pragma: export
#include "mantle.hpp"          // IWYU pragma: export
#include "misc.hpp"            // IWYU pragma: export
#include "net.hpp"             // IWYU pragma: export
#include "pcache.hpp"          // IWYU pragma: export
#include "pix.hpp"             // IWYU pragma: export
#include "pmem.hpp"            // IWYU pragma: export
#include "quake.hpp"           // IWYU pragma: export
#include "render.hpp"          // IWYU pragma: export
#include "rope.hpp"            // IWYU pragma: export
#include "scr/actorscr.hpp"    // IWYU pragma: export
#include "scr/bgscr.hpp"       // IWYU pragma: export
#include "scr/cgscr.hpp"       // IWYU pragma: export
#include "scr/core.hpp"        // IWYU pragma: export
#include "scr/cscr.hpp"        // IWYU pragma: export
#include "scr/gscr.hpp"        // IWYU pragma: export
#include "scr/scr.hpp"         // IWYU pragma: export
#include "scr/sentientscr.hpp" // IWYU pragma: export
#include "scr/vehiclescr.hpp"  // IWYU pragma: export
#include "seh.hpp"             // IWYU pragma: export
#include "sl.hpp"              // IWYU pragma: export
#include "snd/sd.hpp"          // IWYU pragma: export
#include "snd/snd.hpp"         // IWYU pragma: export
#include "snd/sndl.hpp"        // IWYU pragma: export
#include "sv.hpp"              // IWYU pragma: export
#include "s_wcd.hpp"           // IWYU pragma: export
#include "sys.hpp"             // IWYU pragma: export
#include "ugc.hpp"             // IWYU pragma: export
#include "ui/core.hpp"         // IWYU pragma: export
#include "ui/hud.hpp"          // IWYU pragma: export
#include "ui/ui.hpp"           // IWYU pragma: export
#include "utils.hpp"           // IWYU pragma: export

#endif