#pragma once
#ifdef GAME_HPP
#include "bg.hpp"        // IWYU pragma: export
#include "cbuf.hpp"      // IWYU pragma: export
#include "cg/cg.hpp"     // IWYU pragma: export
#include "cinematic.hpp" // IWYU pragma: export
#include "cl.hpp"        // IWYU pragma: export
#include "cmd.hpp"       // IWYU pragma: export
#include "com.hpp"       // IWYU pragma: export
#include "console.hpp"   // IWYU pragma: export
#include "db/db.hpp"     // IWYU pragma: export
#include "demo.hpp"      // IWYU pragma: export
#include "dvar.hpp"      // IWYU pragma: export
#include "dw/dw.hpp"     // IWYU pragma: export
#include "fs.hpp"        // IWYU pragma: export
#include "fx.hpp"        // IWYU pragma: export
#include "game.hpp"      // IWYU pragma: export
#include "gfx.hpp"       // IWYU pragma: export
#include "glasssv.hpp"   // IWYU pragma: export
#include "hunk.hpp"      // IWYU pragma: export
#include "ik.hpp"        // IWYU pragma: export
#include "info.hpp"      // IWYU pragma: export
#include "jq.hpp"        // IWYU pragma: export
#include "level.hpp"     // IWYU pragma: export
#include "live/live.hpp" // IWYU pragma: export
#include "lobby.hpp"     // IWYU pragma: export
#include "macros.hpp"    // IWYU pragma: export
#include "mantle.hpp"    // IWYU pragma: export
#include "misc.hpp"      // IWYU pragma: export
#include "net/net.hpp"   // IWYU pragma: export
#include "pcache.hpp"    // IWYU pragma: export
#include "pix.hpp"       // IWYU pragma: export
#include "pmem.hpp"      // IWYU pragma: export
#include "quake.hpp"     // IWYU pragma: export
#include "render.hpp"    // IWYU pragma: export
#include "rope.hpp"      // IWYU pragma: export
#include "scr/scr.hpp"   // IWYU pragma: export
#include "seh.hpp"       // IWYU pragma: export
#include "sl.hpp"        // IWYU pragma: export
#include "snd/snd.hpp"   // IWYU pragma: export
#include "sv.hpp"        // IWYU pragma: export
#include "s_wcd.hpp"     // IWYU pragma: export
#include "steam.hpp"     // IWYU pragma: export
#include "stream.hpp"    // IWYU pragma: export
#include "sys.hpp"       // IWYU pragma: export
#include "ugc.hpp"       // IWYU pragma: export
#include "ui/ui.hpp"     // IWYU pragma: export
#include "utils.hpp"     // IWYU pragma: export
#endif