#include <std_include.hpp>

#include "bg.hpp"

namespace game {
namespace scr {
namespace builtin {
namespace table {
namespace bg {

constexpr std::array<const char *, CommonFunctionTable::COUNT>
    CommonFunctionTable::names = {
        "ClearAllCharacterTables",
        "GetCharacterBodyStyleIndex",
        "GetAllCharacterBodies",
        "GetAllCharacterHeads",
        "GetCharacterBodyModelCount",
        "GetCharacterBodyModelColorCount",
        "GetCharacterHelmetModelCount",
        "GetCharacterHelmetModelColorCount",
        "GetAnimForCharacter",
        "GetXCamForCharacter",
        "GetSpawnStructForCharacter",
        "GetWeaponModelForCharacter",
        "GetWeaponForCharacter",
        "GetCharacterFields",
        "GetCharacterDisplayName",
        "GetCharacterAssetName",
        "GetCharacterBodyModel",
        "GetCharacterHelmetModel",
        "GetCharacterHelmetHidesHead",
        "GetCharacterHeadModel",
        "GetCharacterBodyRenderOptions",
        "GetCharacterHelmetRenderOptions",
        "GetCharacterHeadRenderOptions",
        "GetCharacterModeRenderOptions",
        "GetXModelCenterOffset",
        "GetNextMap",
        "GetMapOrder",
        "GetMapAtIndex",
        "GetMapIntroMovie",
        "GetMapOutroMovie",
        "GetMapFields",
        "SetupFieldOpsKitLoadouts",
        "SessionModeIsCampaignZombiesGame",
        "IsArchetypeLoaded",
};
DEFINE_NAME_MAP(CommonFunctionTable::names, CommonFunctionTable::hashes);

constexpr std::array<const char *, MathFunctionTable::COUNT>
    MathFunctionTable::names = {
        "Log",
        "Sin",
        "Cos",
        "Tan",
        "Asin",
        "Acos",
        "Atan",
        "Abs",
        "Min",
        "Max",
        "Floor",
        "Ceil",
        "Sqrt",
        "Pow",
        "LerpFloat",
        "LerpVector",
        "GetMinBitCountForNum",
        "MapFloat",
        "DiffTrack",
        "DiffTrackAngle",
        "PackRgba",
        "Int",
        "CastFloat",
        "Distance2DSquared",
        "AngleLerp",
        "RotatePoint",
        "VectorFromLineToPoint",
        "PointOnSegmentNearestToPoint",
        "Distance",
        "Distance2D",
        "DistanceSquared",
        "Length",
        "LengthSquared",
        "Closer",
        "VectorDot",
        "VectorCross",
        "VectorNormalize",
        "VectorProjection",
        "VectorToAngles",
        "VectorLerp",
        "AnglesToUp",
        "AnglesToRight",
        "AnglesToForward",
        "CombineAngles",
        "AngleClamp180",
        "AbsAngleClamp180",
        "AbsAngleClamp360",
        "ForwardRotateAroundUpByAngle",
        "RotatePointAroundAxis",
};
DEFINE_NAME_MAP(MathFunctionTable::names, MathFunctionTable::hashes);

constexpr std::array<const char *, WeaponFunctionTable::COUNT>
    WeaponFunctionTable::names = {"EnumerateWeapons"};
DEFINE_NAME_MAP(WeaponFunctionTable::names, WeaponFunctionTable::hashes);

constexpr std::array<const char *, UtilFunctionTable::COUNT>
    UtilFunctionTable::names = {"GetDvarString",
                                "GetDvarInt",
                                "GetDvarFloat",
                                "GetDvarVector",
                                "Throw",
                                "Array",
                                "AssociativeArray",
                                "ArrayRemoveValue",
                                "ArrayRemoveIndex",
                                "ArrayInsert",
                                "ArrayCombine",
                                "ArrayCopy",
                                "IsInArray",
                                "GetArrayKeys",
                                "GetFirstArrayKey",
                                "GetNextArrayKey",
                                "GetLastArrayKey",
                                "GetPrevArrayKey",
                                "ArrayIntersect",
                                "ArrayGetClosest",
                                "ArrayGetFarthest",
                                "GetStructField",
                                "IsFunctionPtr",
                                "IsString",
                                "IsArray",
                                "IsWeapon",
                                "IsInt",
                                "IsFloat",
                                "IsVec",
                                "IsClass",
                                "IString",
                                "IsSubStr",
                                "GetSubStr",
                                "ToLower",
                                "ToUpper",
                                "StrTok",
                                "StrTok2",
                                "StrStartsWith",
                                "StrEndsWith",
                                "StrIsNumber",
                                "StrIsFloat",
                                "StrIsInt",
                                "StrStrip",
                                "MakeLocalizedString",
                                "SPrintf",
                                "TableLookup",
                                "TableLookupIString",
                                "TableLookupRowNum",
                                "TableLookupColumnForRow",
                                "TableLookupFindCoreAsset",
                                "TableLookupRowCount",
                                "TableLookupColumnCount",
                                "TableLookupRow",
                                "GetItemIndexFromRef",
                                "GetAttachmentTableIndex",
                                "OpenFile",
                                "CloseFile",
                                "FPrintln",
                                "FPrintFields",
                                "FReadLn",
                                "FGetArg",
                                "DebugBreak",
                                "Assert",
                                "AssertMsg",
                                "ErrorMsg",
                                "IsPC",
                                "IsProfileBuild",
                                "IsUsingMods",
                                "Modvar"};
DEFINE_NAME_MAP(UtilFunctionTable::names, UtilFunctionTable::hashes);

} // namespace bg
} // namespace table
} // namespace builtin
} // namespace scr
} // namespace game
