#pragma once

#include <cstdint>
namespace game {
namespace ui {
namespace lua {
enum class PresencePrimary : int32_t {
  PRESENCE_PRIMARY_UNKNOWN = -1,
  PRESENCE_PRIMARY_OFFLINE = 0,
  PRESENCE_PRIMARY_ONLINE = 1,
  PRESENCE_PRIMARY_LOCAL = 2,
  PRESENCE_PRIMARY_TITLE = 3,
  PRESENCE_PRIMARY_AWAY = 4,
  PRESENCE_PRIMARY_BLOCKED = 5,
};
enum class PresenceActivity : int32_t {
  PRESENCE_ACTIVITY_MENU_FIRST = 0,
  PRESENCE_ACTIVITY_UNKNOWN = 0,
  PRESENCE_ACTIVITY_OFFLINE = 0,
  PRESENCE_ACTIVITY_ONLINE_NOT_IN_TITLE = 1,
  PRESENCE_ACTIVITY_MENU_INLOBBY = 2,
  PRESENCE_ACTIVITY_MENU_LOOKING_FOR_PARTY = 3,
  PRESENCE_ACTIVITY_MENU_LOOKING_FOR_PLAYERS = 4,
  PRESENCE_ACTIVITY_MENU_LOCAL = 5,
  PRESENCE_ACTIVITY_MENU_START = 6,
  PRESENCE_ACTIVITY_IN_TITLE = 7,
  PRESENCE_ACTIVITY_NOT_IN_TITLE = 8,
  PRESENCE_ACTIVITY_MENU_LAST = 15,
  PRESENCE_ACTIVITY_CP_FIRST = 16,
  PRESENCE_ACTIVITY_CP_PLAYING_COOP_ON_MAP = 17,
  PRESENCE_ACTIVITY_CP_PLAYING_SOLO_ON_MAP = 18,
  PRESENCE_ACTIVITY_CP_PLAYING_COOP_IN_SAFEHOUSE = 19,
  PRESENCE_ACTIVITY_CP_PLAYING_SOLO_IN_SAFEHOUSE = 20,
  PRESENCE_ACTIVITY_CP_IN_LOBBY = 21,
  PRESENCE_ACTIVITY_CP_WATCHING_FILM = 22,
  PRESENCE_ACTIVITY_CP_LOOKING_FOR_PARTY = 23,
  PRESENCE_ACTIVITY_CP_LOOKING_FOR_PLAYERS = 24,
  PRESENCE_ACTIVITY_CP_PLAYING_LOCAL = 25,
  PRESENCE_ACTIVITY_CP_LAST = 31,
  PRESENCE_ACTIVITY_MP_FIRST = 32,
  PRESENCE_ACTIVITY_MP_PLAYING_GMODE_ON_MAP = 33,
  PRESENCE_ACTIVITY_MP_IN_LOBBY = 34,
  PRESENCE_ACTIVITY_MP_WATCHING_FILM = 35,
  PRESENCE_ACTIVITY_MP_LOOKING_FOR_PARTY = 36,
  PRESENCE_ACTIVITY_MP_LOOKING_FOR_PLAYERS = 37,
  PRESENCE_ACTIVITY_MP_PLAYING_LOCAL = 38,
  PRESENCE_ACTIVITY_MP_LAST = 47,
  PRESENCE_ACTIVITY_ZM_FIRST = 48,
  PRESENCE_ACTIVITY_ZM_PLAYING_MAP_ON_ROUND = 49,
  PRESENCE_ACTIVITY_ZM_IN_LOBBY = 50,
  PRESENCE_ACTIVITY_ZM_WATCHING_FILM = 51,
  PRESENCE_ACTIVITY_ZM_LOOKING_FOR_PARTY = 52,
  PRESENCE_ACTIVITY_ZM_LOOKING_FOR_PLAYERS = 53,
  PRESENCE_ACTIVITY_ZM_PLAYING_LOCAL = 54,
  PRESENCE_ACTIVITY_ZM_LAST = 63,
  PRESENCE_ACTIVITY_LAST = 64,
};
enum class PresenceCtx : int32_t {
  PRESENCE_CTX_MENU_FIRST = 0,
  PRESENCE_CTX_UNKNOWN = 0,
  PRESENCE_CTX_MENU_MODE_SELECT = 1,
  PRESENCE_CTX_MENU_START = 2,
  PRESENCE_CTX_MENU_NOT_ACTIVE = 3,
  PRESENCE_CTX_MENU_LAST = 15,
  PRESENCE_CTX_CP_FIRST = 16,
  PRESENCE_CTX_CP_MAIN_MENU = 17,
  PRESENCE_CTX_CP_PRIVATE_GAME = 18,
  PRESENCE_CTX_CP_PUBLIC_MATCH = 19,
  PRESENCE_CTX_CP_THEATER = 20,
  PRESENCE_CTX_CP_LAST = 31,
  PRESENCE_CTX_MP_FIRST = 32,
  PRESENCE_CTX_MP_MAIN_MENU = 33,
  PRESENCE_CTX_MP_CUSTOM_GAMES = 34,
  PRESENCE_CTX_MP_PUBLIC_MATCH = 35,
  PRESENCE_CTX_MP_THEATER = 36,
  PRESENCE_CTX_MP_LAST = 47,
  PRESENCE_CTX_ZM_FIRST = 48,
  PRESENCE_CTX_ZM_MAIN_MENU = 49,
  PRESENCE_CTX_ZM_PRIVATE_GAME = 50,
  PRESENCE_CTX_ZM_PUBLIC_MATCH = 51,
  PRESENCE_CTX_ZM_THEATER = 52,
  PRESENCE_CTX_ZM_LAST = 63,
  PRESENCE_CTX_LAST = 64,
};
enum class PresenceFilter : int32_t {
  PRESENCE_FILTER_ALL = 0,
  PRESENCE_FILTER_ONLINE_AND_NOT_IN_TITLE = 1,
  PRESENCE_FILTER_ONLINE_AND_IN_TITLE = 2,
  PRESENCE_FILTER_ONLINE = 3,
  PRESENCE_FILTER_CACHED = 255,
};
enum class PresenceSorting : int32_t {
  PRESENCE_SORTING_UNSORTED = 0,
  PRESENCE_SORTING_ONLINE_MOST_RECENT = 1,
  PRESENCE_SORTING_ALPHABETICAL = 2,
};
enum class GroupMenu : int32_t {
  GROUP_MENU_DEFAULT = 0,
  GROUP_MENU_HOME = 0,
  GROUP_MENU_ROSTER = 1,
  GROUP_MENU_BADGES = 2,
  GROUP_MENU_LEADERBOARD = 3,
  GROUP_MENU_SHARE = 4,
  GROUP_MENU_ADMIN = 5,
  GROUP_MENU_COUNT = 6,
};
enum class GroupMemberStatus : int32_t {
  GROUP_MEMBER_STATUS_MEMBER = 0,
  GROUP_MEMBER_STATUS_ADMIN = 1,
  GROUP_MEMBER_STATUS_OWNER = 2,
  GROUP_MEMBER_STATUS_COUNT = 3,
  GROUP_MEMBER_STATUS_INVALID = 3,
};
enum class GroupPrivacy : int32_t {
  GROUP_PRIVACY_PUBLIC = 0,
  GROUP_PRIVACY_PRIVATE = 1,
  GROUP_PRIVACY_COUNT = 2,
};
enum class GroupApplicationState : int32_t {
  GROUP_APPLICATION_STATE_NONE = 0,
  GROUP_APPLICATION_STATE_PENDING = 1,
  GROUP_APPLICATION_STATE_REJECTED = 2,
  GROUP_APPLICATION_STATE_WITHDRAWN = 3,
};
enum class GroupBufferType : int32_t {
  GROUP_BUFFER_TYPE_SELF = 0,
  GROUP_BUFFER_TYPE_SEARCH = 1,
  GROUP_BUFFER_TYPE_COUNT = 2,
  GROUP_BUFFER_TYPE_FIRST = 0,
  GROUP_BUFFER_TYPE_INVALID = 2,
};
enum class GroupSearchType : int32_t {
  GROUP_SEARCH_TYPE_INVALID = 0,
  GROUP_SEARCH_TYPE_FRIENDS = 1,
  GROUP_SEARCH_TYPE_SELECTED_FRIEND = 2,
  GROUP_SEARCH_TYPE_POPULAR = 3,
  GROUP_SEARCH_TYPE_SEARCH_BY_PARAMS = 4,
  GROUP_SEARCH_TYPE_COUNT = 5,
};
enum class GroupJoinApprovalType : int32_t {
  GROUP_JOIN_APPROVAL_OFF = 0,
  GROUP_JOIN_APPROVAL_ON = 1,
  GROUP_JOIN_APPROVAL_INVITE_ONLY = 2,
  GROUP_JOIN_APPROVAL_TYPE_INVALID = 3,
};
enum class GroupAdminPrivilege : int32_t {
  GROUP_ADMIN_PRIVILEGE_INVITE_PLAYERS = 0,
  GROUP_ADMIN_PRIVILEGE_APPROVE_JOIN_REQUESTS = 1,
  GROUP_ADMIN_PRIVILEGE_REMOVE_MEMBERS = 2,
  GROUP_ADMIN_PRIVILEGE_BAN_MEMBERS = 3,
  GROUP_ADMIN_PRIVILEGE_FAVORITE_SHOWCASE_CONTENT = 4,
  GROUP_ADMIN_PRIVILEGE_REMOVE_SHOWCASE_CONTENT = 5,
  GROUP_ADMIN_PRIVILEGE_BLOCK_MEMBER_CONTENT = 6,
  GROUP_ADMIN_PRIVILEGE_EDIT_FEATURED_CONTENT = 7,
  GROUP_ADMIN_PRIVILEGE_EDIT_GROUP_MESSAGE = 8,
  GROUP_ADMIN_PRIVILEGE_EDIT_GROUP_LEADERBOARD = 9,
  GROUP_ADMIN_PRIVILEGE_EDIT_GROUP_EMBLEM = 10,
  GROUP_ADMIN_PRIVILEGE_EDIT_GROUP_DESCRIPTION = 11,
  GROUP_ADMIN_PRIVILEGE_EDIT_GROUP_TYPE = 12,
  GROUP_ADMIN_PRIVILEGE_EDIT_GROUP_NAME = 13,
  GROUP_ADMIN_PRIVILEGE_MANAGE_ADMINS = 14,
  GROUP_ADMIN_PRIVILEGE_COUNT = 15,
  GROUP_ADMIN_PRIVILEGE_TYPE_INVALID = 15,
};
enum class GroupSearchSizeRangeIndex : int32_t {
  GROUP_SEARCH_SIZE_RANGE_INDEX_1 = 0,
  GROUP_SEARCH_SIZE_RANGE_INDEX_FIRST = 0,
  GROUP_SEARCH_SIZE_RANGE_INDEX_2 = 1,
  GROUP_SEARCH_SIZE_RANGE_INDEX_3 = 2,
  GROUP_SEARCH_SIZE_RANGE_INDEX_4 = 3,
  GROUP_SEARCH_SIZE_RANGE_INDEX_LAST = 3,
  GROUP_SEARCH_SIZE_RANGE_COUNT = 4,
  GROUP_SEARCH_SIZE_RANGE_INDEX_ANY = 4,
};
enum class GroupUpdateGamertagsType : int32_t {
  GROUP_UPDATE_GAMERTAGS_TYPE_INVITES = 0,
  GROUP_UPDATE_GAMERTAGS_TYPE_GROUP_MEMBERS = 1,
  GROUP_UPDATE_GAMERTAGS_TYPE_COUNT = 2,
};
enum class GroupUpdatePrivacyType : int32_t {
  GROUP_UPDATE_PRIVACY_TYPE_QUICKJOIN = 0,
  GROUP_UPDATE_PRIVACY_TYPE_GROUP_MEMBERS = 1,
  GROUP_UPDATE_PRIVACY_TYPE_COUNT = 2,
};
enum class connectionType_e : int32_t {
  CONNECTION_TYPE_UNKNOWN = 0,
  CONNECTION_TYPE_WIRED = 1,
  CONNECTION_TYPE_WIRELESS = 2,
};
enum class XONLINE_NAT_TYPE : int32_t {
  XONLINE_NAT_UNKNOWN = 0,
  XONLINE_NAT_OPEN = 1,
  XONLINE_NAT_MODERATE = 2,
  XONLINE_NAT_STRICT = 3,
  XONLINE_NAT_TYPE_COUNT = 4,
};
enum class LiveInternalEvent : int32_t {
  LIVE_INTERNAL_EVENT_FIRST = 0,
  LIVE_INTERNAL_EVENT_RESERVED = 0,
  LIVE_INTERNAL_EVENT_FRIENDS_LIST_UPDATED = 1,
  LIVE_INTERNAL_EVENT_FRIENDS_PRESENCE_UPDATED = 2,
  LIVE_INTERNAL_EVENT_QUICKJOIN_PRESENCE_UPDATED = 3,
  LIVE_INTERNAL_EVENT_COUNT = 4,
};
enum class SYSINFO : int32_t {
  SYSINFO_VERSION_NUMBER = 0,
  SYSINFO_CONNECTIVITY_INFO = 1,
  SYSINFO_NAT_TYPE = 2,
  SYSINFO_CUSTOMER_SUPPORT_LINK = 3,
  SYSINFO_BANDWIDTH = 4,
  SYSINFO_IP_ADDRESS = 5,
  SYSINFO_EXTERNAL_IP_ADDRESS = 6,
  SYSINFO_INTERNAL_IP_ADDRESS = 7,
  SYSINFO_GEOGRAPHICAL_REGION = 8,
  SYSINFO_Q = 9,
  SYSINFO_CONSOLE_ID = 10,
  SYSINFO_MAC_ADDRESS = 11,
  SYSINFO_NAT_TYPE_LOBBY = 12,
  SYSINFO_CONNECTION_TYPE = 13,
};
enum class demoCameraMode : int32_t {
  DEMO_CAMERA_MODE_NONE = 0,
  DEMO_CAMERA_MODE_THIRDPERSON = 1,
  DEMO_CAMERA_MODE_FREECAM = 2,
  DEMO_CAMERA_MODE_COUNT = 3,
};
enum class demoFreeCameraMode : int32_t {
  DEMO_FREECAM_MODE_FREEROAM = 0,
  DEMO_FREECAM_MODE_EDIT = 1,
  DEMO_FREECAM_MODE_DOLLY = 2,
  DEMO_FREECAM_MODE_LOCK_ON = 3,
  DEMO_FREECAM_MODE_LIGHTMAN = 4,
  DEMO_FREECAM_MODE_COUNT = 5,
  DEMO_FREECAM_MODE_FIRST = 0,
  DEMO_FREECAM_MODE_LAST = 2,
};
enum class demoLightmanLightMode : int32_t {
  DEMO_LIGHTMAN_LIGHT_MODE_OMNI = 0,
  DEMO_LIGHTMAN_LIGHT_MODE_SPOT = 1,
  DEMO_LIGHTMAN_LIGHT_MODE_COUNT = 2,
};
enum class demoClipState : int32_t {
  DEMO_CLIP_IDLE = 0,
  DEMO_CLIP_RECORD_UNCOMPRESSED_SNAPHOT = 1,
  DEMO_CLIP_RECORD_CONTINUOUS = 2,
  DEMO_CLIP_PAUSED = 3,
  DEMO_CLIP_PREVIEW = 4,
  DEMO_CLIP_STREAMING = 5,
};
enum class demoClipTransition : int32_t {
  DEMO_CLIP_TRANSITION_NONE = 0,
  DEMO_CLIP_TRANSITION_FADE = 1,
  DEMO_CLIP_TRANSITION_COUNT = 2,
  DEMO_CLIP_TRANSITION_FIRST = 0,
  DEMO_CLIP_TRANSITION_LAST = 1,
};
enum class demoContextMode : int32_t {
  DEMO_CONTEXT_MODE_PLAYBACK = 0,
  DEMO_CONTEXT_MODE_BASIC = 1,
  DEMO_CONTEXT_MODE_DIRECTOR = 2,
  DEMO_CONTEXT_MODE_OBJECT_LINK = 3,
  DEMO_CONTEXT_MODE_LIGHTER = 4,
  DEMO_CONTEXT_MODE_HIGHLIGHT_REEL = 5,
};
enum class demoDollyCameraTimeScaleMode : int32_t {
  DEMO_DOLLYCAM_TIMESCALE_MODE_MANUAL = 0,
  DEMO_DOLLYCAM_TIMESCALE_MODE_LINEAR = 1,
  DEMO_DOLLYCAM_TIMESCALE_MODE_FIXED = 2,
  DEMO_DOLLYCAM_TIMESCALE_MODE_COUNT = 3,
};
enum class demoInformationScreenTypes : int32_t {
  DEMO_INFORMATION_SCREEN_NONE = 0,
  DEMO_INFORMATION_SCREEN_FILM_START_SCREEN_FADE_IN = 1,
  DEMO_INFORMATION_SCREEN_FILM_START_SCREEN_FADE_OUT = 2,
  DEMO_INFORMATION_SCREEN_TRANSITION = 3,
  DEMO_INFORMATION_SCREEN_WAITING_FOR_DOWNLOAD = 4,
  DEMO_INFORMATION_SCREEN_COUNT = 5,
};
enum class demoHighlightReelPlayerFilter : int32_t {
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_ONLY_ME = 0,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_FRIENDS = 1,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_ME_AND_FRIENDS = 2,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_ONLY_FRIENDLY_TEAM = 3,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_ONLY_ENEMY_TEAM = 4,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_EVERYONE = 5,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_FIRST = 0,
  DEMO_HIGHLIGHT_REEL_PLAYER_FILTER_LAST = 5,
};
enum class demoHighlightReelTransitionFilter : int32_t {
  DEMO_HIGHLIGHT_REEL_TRANSITION_FILTER_NONE = 0,
  DEMO_HIGHLIGHT_REEL_TRANSITION_FILTER_FADE = 1,
  DEMO_HIGHLIGHT_REEL_TRANSITION_FILTER_RANDOM = 2,
  DEMO_HIGHLIGHT_REEL_TRANSITION_FILTER_FIRST = 0,
  DEMO_HIGHLIGHT_REEL_TRANSITION_FILTER_LAST = 2,
};
enum class demoHighlightReelStylesFilter : int32_t {
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_BEST_MOMENTS = 0,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_EXPLOSIVE_AND_PROJECTILE_KILLS = 1,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_VEHICLE_KILLS = 2,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_GUN_KILLS_ONLY = 3,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_GUN_KILLS_AND_EVENTS = 4,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_DOG_KILLS = 5,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_ZM_RAMPAGER = 6,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_ZM_SAVIOR_AND_SINNER = 7,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_ZM_TEAM_PLAYER = 8,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_ZM_BIG_SPENDER = 9,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_ZM_HANDYMAN = 10,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_FIRST = 0,
  DEMO_HIGHLIGHT_REEL_STYLES_FILTER_LAST = 10,
};
enum class demoHighlightReelGameResultFilter : int32_t {
  DEMO_HIGHLIGHT_REEL_GAME_RESULT_FILTER_OFF = 0,
  DEMO_HIGHLIGHT_REEL_GAME_RESULT_FILTER_FINAL_RESULT = 1,
  DEMO_HIGHLIGHT_REEL_GAME_RESULT_FILTER_WITH_EVENTS = 2,
  DEMO_HIGHLIGHT_REEL_GAME_RESULT_FILTER_ALL_RESULTS = 3,
  DEMO_HIGHLIGHT_REEL_GAME_RESULT_FILTER_FIRST = 0,
  DEMO_HIGHLIGHT_REEL_GAME_RESULT_FILTER_LAST = 3,
};
enum class LobbyClientType : int32_t {
  LOBBY_CLIENT_TYPE_INVALID = -1,
  LOBBY_CLIENT_TYPE_ALL = 0,
  LOBBY_CLIENT_TYPE_LOCAL = 1,
  LOBBY_CLIENT_TYPE_REMOTE = 2,
  LOBBY_CLIENT_TYPE_SPLITSCREEN_ALL = 3,
  LOBBY_CLIENT_TYPE_SPLITSCREEN_REMOTE = 4,
  LOBBY_CLIENT_TYPE_GUEST = 5,
};
enum class LobbyType : int32_t {
  LOBBY_TYPE_INVALID = -1,
  LOBBY_TYPE_PRIVATE = 0,
  LOBBY_TYPE_GAME = 1,
  LOBBY_TYPE_COUNT = 2,
  LOBBY_TYPE_FIRST = 0,
  LOBBY_TYPE_LAST = 1,
};
enum class LobbyModule : int32_t {
  LOBBY_MODULE_INVALID = -1,
  LOBBY_MODULE_HOST = 0,
  LOBBY_MODULE_CLIENT = 1,
  LOBBY_MODULE_COUNT = 2,
  LOBBY_MODULE_FIRST = 0,
  LOBBY_MODULE_LAST = 1,
  LOBBY_MODULE_PEER_TO_PEER = 3,
};
enum class LobbyMode : int32_t {
  LOBBY_MODE_INVALID = -1,
  LOBBY_MODE_PUBLIC = 0,
  LOBBY_MODE_CUSTOM = 1,
  LOBBY_MODE_THEATER = 2,
  LOBBY_MODE_ARENA = 3,
  LOBBY_MODE_FREERUN = 4,
  LOBBY_MODE_COUNT = 5,
};
enum class LobbyNetworkMode : int32_t {
  LOBBY_NETWORKMODE_INVALID = -1,
  LOBBY_NETWORKMODE_UNKNOWN = 0,
  LOBBY_NETWORKMODE_LAN = 1,
  LOBBY_NETWORKMODE_LIVE = 2,
  LOBBY_NETWORKMODE_COUNT = 3,
  LOBBY_NETWORKMODE_LOCAL = 1,
};
enum class PartyPrivacy : int32_t {
  PARTY_PRIVACY_OPEN = 0,
  PARTY_PRIVACY_FRIENDS_ONLY = 1,
  PARTY_PRIVACY_INVITE_ONLY = 2,
  PARTY_PRIVACY_CLOSED = 3,
  PARTY_PRIVACY_COUNT = 4,
};
enum class LobbyJoinable : int32_t {
  LOBBY_JOINABLE_NO_NOT_IN_LOBBY = 0,
  LOBBY_JOINABLE_YES = 1,
  LOBBY_JOINABLE_YES_FRIENDS_ONLY = 2,
  LOBBY_JOINABLE_NO_PARTY_PRIVACY_INVITE_ONLY = 3,
  LOBBY_JOINABLE_NO_PARTY_PRIVACY_CLOSED = 4,
  LOBBY_JOINABLE_NO_PARTY_FULL = 5,
  LOBBY_JOINABLE_NO_GAME_FULL = 6,
  LOBBY_JOINABLE_NO_PLAYING_LOCAL = 7,
  LOBBY_JOINABLE_NO_GAME_PAUSED = 8,
  LOBBY_JOINABLE_NO = 9,
  LOBBY_JOINABLE_NO_YOU_NEED_DLC = 10,
  LOBBY_JOINABLE_COUNT = 11,
};
enum class LobbyMainMode : int32_t {
  LOBBY_MAINMODE_INVALID = -1,
  LOBBY_MAINMODE_CP = 0,
  LOBBY_MAINMODE_MP = 1,
  LOBBY_MAINMODE_ZM = 2,
  LOBBY_MAINMODE_COUNT = 3,
};
enum class LobbyHostType : int32_t {
  LOBBY_HOSTTYPE_INVALID = -1,
  LOBBY_HOSTTYPE_P2P = 0,
  LOBBY_HOSTTYPE_DEDICATED = 1,
  LOBBY_HOSTTYPE_COUNT = 2,
};
enum class LobbyMapVote : int32_t {
  LOBBY_MAPVOTE_INVALID = -1,
  LOBBY_MAPVOTE_NONE = 0,
  LOBBY_MAPVOTE_NEXT = 1,
  LOBBY_MAPVOTE_PREVIOUS = 2,
  LOBBY_MAPVOTE_RANDOM = 3,
};
enum class LobbyProcessComplete : int32_t {
  LOBBY_PROCESS_COMPLETE_INVALID = -1,
  LOBBY_PROCESS_COMPLETE_SUCCESS = 0,
  LOBBY_PROCESS_COMPLETE_FAILURE = 1,
  LOBBY_PROCESS_COMPLETE_ERROR = 2,
};
enum class LobbyDisconnectClient : int32_t {
  LOBBY_DISCONNECT_CLIENT_INVALID = -1,
  LOBBY_DISCONNECT_CLIENT_DROP = 0,
  LOBBY_DISCONNECT_CLIENT_KICK = 1,
  LOBBY_DISCONNECT_CLIENT_BADDLC = 2,
  LOBBY_DISCONNECT_CLIENT_KICK_PARTY = 3,
  LOBBY_DISCONNECT_CLIENT_HOSTRELOAD = 4,
  LOBBY_DISCONNECT_CLIENT_NOPARTYCHAT = 5,
  LOBBY_DISCONNECT_CLIENT_ERROR = 6,
  LOBBY_DISCONNECT_CLIENT_MISSING_CONTENT = 7,
};
enum class LiveUserState : int32_t {
  LIVE_USER_INVALID = -1,
  LIVE_USER_SIGNED_IN = 0,
  LIVE_USER_SIGNED_OUT = 1,
  LIVE_USER_COUNT = 2,
};
enum class SessionStatus : int32_t {
  SESSION_STATUS_INVALID = -1,
  SESSION_STATUS_IDLE = 0,
  SESSION_STATUS_JOIN = 1,
  SESSION_STATUS_MERGE = 2,
  SESSION_STATUS_MIGRATE = 3,
  SESSION_STATUS_PAUSED = 4,
  SESSION_STATUS_ERROR = 5,
  SESSION_STATUS_COUNT = 6,
};
enum class QueryID : int32_t {
  QUERYID_SEARCH_SESSIONS_INVALID = 0,
  QUERYID_SEARCH_SESSIONS_BY_PLAYLIST_VERSION = 1,
  QUERYID_SEARCH_SESSIONS_ALL = 2,
  QUERYID_SEARCH_SESSION_BY_GAME_SECURITY_ID = 3,
  QUERYID_SEARCH_SESSION_DEDICATED = 4,
  QUERYID_SEARCH_SESSION_DEDICATED_PARKED = 5,
  QUERYID_SEARCH_SESSIONS_BY_SERVER_TYPE = 6,
};
enum class ShowInMatchmaking : int32_t {
  SHOW_IN_MATCHMAKING_FALSE = 0,
  SHOW_IN_MATCHMAKING_TRUE = 1,
};
enum class LaunchGameState : int32_t {
  LAUNCH_GAME_STATE_START = 0,
  LAUNCH_GAME_STATE_PUMP = 1,
  LAUNCH_GAME_STATE_CLEAR = 2,
  LAUNCH_GAME_STATE_COUNT = 3,
};
enum class LobbyOnlineState : int32_t {
  LOBBY_ONLINE_STATE_IDLE = 0,
  LOBBY_ONLINE_STATE_ACTIVE = 1,
  LOBBY_ONLINE_STATE_CREATE = 2,
  LOBBY_ONLINE_STATE_UPDATE = 3,
  LOBBY_ONLINE_STATE_DELETE = 4,
  LOBBY_ONLINE_STATE_ERROR = 5,
};
enum class LobbyOnlineUpdateEventType : int32_t {
  LOBBY_ONLINE_UPDATE_PUMP = 0,
  LOBBY_ONLINE_UPDATE_SUCCESS = 1,
  LOBBY_ONLINE_UPDATE_ERROR = 2,
};
enum class SessionActive : int32_t {
  SESSION_INACTIVE = 0,
  SESSION_KEEP_ALIVE = 1,
  SESSION_ACTIVE = 2,
};
enum class SessionDirty : int32_t {
  SESSION_DIRTY_STATE = 1,
  SESSION_DIRTY_UI = 2,
  SESSION_DIRTY_CLIENT_LIST = 4,
};
enum class PlatformSessions : int32_t {
  PLATFORM_SESSIONS_OFF = 0,
  PLATFORM_SESSIONS_ON_NONFATAL = 1,
  PLATFORM_SESSIONS_ON_NONFATAL_NO_MORE_SESSIONS = 2,
  PLATFORM_SESSIONS_ON_FATAL = 3,
  PLATFORM_SESSIONS_ON_FATAL_NO_MORE_SESSIONS = 4,
  PLATFORM_SESSIONS_COUNT = 4,
};
enum class SteamServerRequestType : int32_t {
  STEAM_SERVER_REQUEST_TYPE_INTERNET = 0,
  STEAM_SERVER_REQUEST_TYPE_LAN = 1,
  STEAM_SERVER_REQUEST_TYPE_FRIENDS = 2,
  STEAM_SERVER_REQUEST_TYPE_FAVORITES = 3,
  STEAM_SERVER_REQUEST_TYPE_HISTORY = 4,
  STEAM_SERVER_REQUEST_TYPE_SPECTATOR = 5,
  STEAM_SERVER_REQUEST_TYPE_ZOMBIES = 6,
  STEAM_SERVER_REQUEST_TYPE_COUNT = 7,
};
enum class SteamServerSortType : int32_t {
  STEAM_SERVER_SORT_TYPE_PROTECTED_ASCENDING = 0,
  STEAM_SERVER_SORT_TYPE_PROTECTED_DESCENDING = 1,
  STEAM_SERVER_SORT_TYPE_DEDICATED_ASCENDING = 2,
  STEAM_SERVER_SORT_TYPE_DEDICATED_DESCENDING = 3,
  STEAM_SERVER_SORT_TYPE_RANKED_ASCENDING = 4,
  STEAM_SERVER_SORT_TYPE_RANKED_DESCENDING = 5,
  STEAM_SERVER_SORT_TYPE_NAME_ASCENDING = 6,
  STEAM_SERVER_SORT_TYPE_NAME_DESCENDING = 7,
  STEAM_SERVER_SORT_TYPE_MAP_ASCENDING = 8,
  STEAM_SERVER_SORT_TYPE_MAP_DESCENDING = 9,
  STEAM_SERVER_SORT_TYPE_HARDCORE_ASCENDING = 10,
  STEAM_SERVER_SORT_TYPE_HARDCORE_DESCENDING = 11,
  STEAM_SERVER_SORT_TYPE_GAMETYPE_ASCENDING = 12,
  STEAM_SERVER_SORT_TYPE_GAMETYPE_DESCENDING = 13,
  STEAM_SERVER_SORT_TYPE_PLAYERS_ASCENDING = 14,
  STEAM_SERVER_SORT_TYPE_PLAYERS_DESCENDING = 15,
  STEAM_SERVER_SORT_TYPE_PING_ASCENDING = 16,
  STEAM_SERVER_SORT_TYPE_PING_DESCENDING = 17,
  STEAM_SERVER_SORT_TYPE_COUNT = 18,
};
enum class SteamServerFilterType : int32_t {
  STEAM_SERVER_BROWSER_FILTERTYPE_MAP = 0,
  STEAM_SERVER_BROWSER_FILTERTYPE_GAMETYPE = 1,
  STEAM_SERVER_BROWSER_FILTERTYPE_MOD = 2,
  STEAM_SERVER_BROWSER_FILTERTYPE_KEYWORDS = 3,
  STEAM_SERVER_BROWSER_FILTERTYPE_COUNT = 4,
};
enum class SteamServerAttributeFilter : int32_t {
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_DEDICATED = 0,
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_NOTDEDICATED = 1,
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_RANKED = 2,
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_UNRANKED = 3,
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_HARDCORE = 4,
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_CORE = 5,
  STEAM_SERVER_BROWSER_ATTRIBUTEFILTER_COUNT = 6,
};
enum class DurangoSessionJoinRestriction : int32_t {
  DURANGO_SESSION_JOIN_RESTRICTION_UNKNOWN = -1,
  DURANGO_SESSION_JOIN_RESTRICTION_NONE = -1,
  DURANGO_SESSION_JOIN_RESTRICTION_LOCAL = -1,
  DURANGO_SESSION_JOIN_RESTRICTION_FOLLOWED = -1,
};
enum class DurangoSessionVisibility : int32_t {
  DURANGO_SESSION_VISIBILITY_UNKNOWN = -1,
  DURANGO_SESSION_VISIBILITY_ANY = -1,
  DURANGO_SESSION_VISIBILITY_PRIVATE = -1,
  DURANGO_SESSION_VISIBILITY_VISIBLE = -1,
  DURANGO_SESSION_VISIBILITY_FULL = -1,
  DURANGO_SESSION_VISIBILITY_OPEN = -1,
};
enum class DurangoWriteSessionStatus : int32_t {
  DURANGO_WRITE_SESSION_STATUS_UNKNOWN = -1,
  DURANGO_WRITE_SESSION_STATUS_ACCESSDENIED = -1,
  DURANGO_WRITE_SESSION_STATUS_CREATED = -1,
  DURANGO_WRITE_SESSION_STATUS_CONFLICT = -1,
  DURANGO_WRITE_SESSION_STATUS_HANDLENOTFOUND = -1,
  DURANGO_WRITE_SESSION_STATUS_OUTOFSYNC = -1,
  DURANGO_WRITE_SESSION_STATUS_SESSIONDELETED = -1,
  DURANGO_WRITE_SESSION_STATUS_UPDATED = -1,
};
enum class LobbyListComparisonType : int32_t {
  LOBBY_LIST_COMPARISON_TYPE_EQUAL_TO_OR_LESS_THAN = -2,
  LOBBY_LIST_COMPARISON_TYPE_LESS_THAN = -1,
  LOBBY_LIST_COMPARISON_TYPE_EQUAL = 0,
  LOBBY_LIST_COMPARISON_TYPE_GREATER_THAN = 1,
  LOBBY_LIST_COMPARISON_TYPE_EQUAL_TO_OR_GREATER_THAN = 2,
  LOBBY_LIST_COMPARISON_TYPE_NOT_EQUAL = 3,
};
enum class GameServerStatus : int32_t {
  GAME_SERVER_STATUS_IDLE = 0,
  GAME_SERVER_STATUS_PRELOADING = 1,
  GAME_SERVER_STATUS_STARTING_SERVER = 2,
  GAME_SERVER_STATUS_MIGRATING = 3,
  GAME_SERVER_STATUS_RUNNING = 4,
  GAME_SERVER_STATUS_RUNNING_DEMO = 5,
};
enum class JoinType : int32_t {
  JOIN_TYPE_NORMAL = 0,
  JOIN_TYPE_PLAYLIST = 1,
  JOIN_TYPE_FRIEND = 2,
  JOIN_TYPE_INVITE = 3,
  JOIN_TYPE_PARTY = 4,
  JOIN_TYPE_GROUPS = 5,
  JOIN_TYPE_COUNT = 6,
};
enum class JoinResult : int32_t {
  JOIN_RESULT_INVALID = 0,
  JOIN_RESULT_SUCCESS = 1,
  JOIN_RESULT_CONNECT_TO_HOST_FAILURE = 2,
  JOIN_RESULT_PROBE_SEND_FAILURE = 3,
  JOIN_RESULT_PROBE_TIMEOUT = 4,
  JOIN_RESULT_PROBE_INVALID_LOBBY = 5,
  JOIN_RESULT_PROBE_INVALID_INFO = 6,
  JOIN_RESULT_PROBE_RESULT_INVALID = 7,
  JOIN_RESULT_INVALID_LOBBY = 8,
  JOIN_RESULT_SEND_AGREEMENT_REQUEST_FAILED = 9,
  JOIN_RESULT_HANDSHAKE_WINDOW_EXPIRED = 10,
  JOIN_RESULT_AGREEMENT_WINDOW_EXPIRED = 11,
  JOIN_RESULT_JOIN_DISABLED = 12,
  JOIN_RESULT_JOIN_ALREADY_IN_PROGRESS = 13,
  JOIN_RESULT_NOT_JOINABLE_OFFLINE_MODE = 14,
  JOIN_RESULT_NOT_JOINABLE_NOT_HOSTING = 15,
  JOIN_RESULT_NOT_JOINABLE_NOT_IDLE = 16,
  JOIN_RESULT_NOT_JOINABLE_CLOSED = 17,
  JOIN_RESULT_NOT_JOINABLE_INVITE_ONLY = 18,
  JOIN_RESULT_NOT_JOINABLE_FRIENDS_ONLY = 19,
  JOIN_RESULT_NOT_JOINABLE_SOLO_MODE = 20,
  JOIN_RESULT_NO_JOIN_IN_PROGRESS = 21,
  JOIN_RESULT_GAME_PAUSED = 22,
  JOIN_RESULT_CHUNK_MP_REQUIRED = 23,
  JOIN_RESULT_CHUNK_ZM_REQUIRED = 24,
  JOIN_RESULT_CHUNK_CP_REQUIRED = 25,
  JOIN_RESULT_CHUNK_MP_REQUIRED_HOST = 26,
  JOIN_RESULT_CHUNK_ZM_REQUIRED_HOST = 27,
  JOIN_RESULT_CHUNK_CP_REQUIRED_HOST = 28,
  JOIN_RESULT_SPLITSCREEN_NOT_ALLOWED = 29,
  JOIN_RESULT_IN_PUBLIC_PROBATION = 30,
  JOIN_RESULT_IN_ARENA_PROBATION = 31,
  JOIN_RESULT_OVER_MAX_PARTY_LIMIT = 32,
  JOIN_RESULT_NO_PARTIES = 33,
  JOIN_RESULT_LOBBY_FULL = 34,
  JOIN_RESULT_NETWORK_MODE_MISMATCH = 35,
  JOIN_RESULT_MISMATCH_PLAYLISTID = 36,
  JOIN_RESULT_MISMATCH_PLAYLIST_VERSION_TO_NEW = 37,
  JOIN_RESULT_MISMATCH_PLAYLIST_VERSION_TO_OLD = 38,
  JOIN_RESULT_MISMATCH_PROTOCOL_VERSION = 39,
  JOIN_RESULT_MISMATCH_NETFIELD_CHECKSUM = 40,
  JOIN_RESULT_MISMATCH_FFOTD_VERSION_TO_NEW = 41,
  JOIN_RESULT_MISMATCH_FFOTD_VERSION_TO_OLD = 42,
  JOIN_RESULT_MIGRATE_IN_PROGRESS = 43,
  JOIN_RESULT_COULD_NOT_RESERVE = 44,
  JOIN_RESULT_BAD_DLC_BITS = 45,
  JOIN_RESULT_BAD_MPHD_BITS = 46,
  JOIN_RESULT_VM_FAILURE_1 = 47,
  JOIN_RESULT_VM_FAILURE_2 = 48,
  JOIN_RESULT_VM_FAILURE_3 = 49,
  JOIN_RESULT_VM_FAILURE_4 = 50,
  JOIN_RESULT_STARTER_PACK_RESTRICT = 51,
  JOIN_RESULT_INVALID_PASSWORD = 52,
  JOIN_RESULT_BANNED = 53,
  JOIN_RESULT_BANNED_MEMBER = 54,
  JOIN_RESULT_UNDER_MIN_PARTY_LIMIT = 55,
  JOIN_RESPONSE_COUNT = 56,
};
enum class LobbyTaskType : int32_t {
  LOBBYTASK_TYPE_HOST_CREATE = 0,
  LOBBYTASK_TYPE_HOST_ADDLOCAL = 1,
  LOBBYTASK_TYPE_HOST_END = 2,
  LOBBYTASK_TYPE_HOST_SEARCH = 3,
  LOBBYTASK_TYPE_HOST_ADVERTISE = 4,
  LOBBYTASK_TYPE_HOST_GAMERTAGSTOXUIDS = 5,
  LOBBYTASK_TYPE_CLIENT_END = 6,
  LOBBYTASK_TYPE_CLIENT_LAUNCH_GAME = 7,
  LOBBYTASK_TYPE_COUNT = 8,
};
enum class LobbyTaskState : int32_t {
  LOBBYTASK_IDLE = 0,
  LOBBYTASK_HOSTCREATE_PENDING = 1,
  LOBBYTASK_HOSTCREATE_DWNET = 2,
  LOBBYTASK_HOSTCREATE_SESSION = 3,
  LOBBYTASK_HOSTEND_PENDING = 4,
  LOBBYTASK_HOSTEND_ONLINE = 5,
  LOBBYTASK_HOSTEND_DISCONNECT = 6,
  LOBBYTASK_HOSTEND_COOLOFF = 7,
  LOBBYTASK_HOSTEND_SHUTDOWN = 8,
  LOBBYTASK_HOSTSEARCH_PENDING = 9,
  LOBBYTASK_HOSTSEARCH_INPROGRESS = 10,
  LOBBYTASK_HOSTSEARCH_BEGINJOIN = 11,
  LOBBYTASK_HOSTSEARCH_JOINING = 12,
  LOBBYTASK_HOSTADVERTISE_PENDING = 13,
  LOBBYTASK_HOSTADVERTISE_INPROGRESS = 14,
  LOBBYTASK_HOSTPLATFORMSESSIONCREATE = 15,
  LOBBYTASK_HOSTPLATFORMSESSIONUPDATE = 16,
  LOBBYTASK_HOSTPLATFORMSESSIONINVITE = 17,
  LOBBYTASK_HOSTPLATFORMSESSIONGETSESSIONINFO = 18,
  LOBBYTASK_HOSTPLATFORMSESSIONGETINVITEINFO = 19,
  LOBBYTASK_HOSTPLATFORMSESSIONLEAVE = 20,
  LOBBYTASK_HOSTPLATFORMSESSIONSEARCH = 21,
  LOBBYTASK_HOSTPLATFORMSESSIONJOIN = 22,
  LOBBYTASK_HOSTPLATFORMSESSIONSETDURANGOJOINRESTRICTION = 23,
  LOBBYTASK_HOSTGAMERTAGSTOXUIDS = 24,
  LOBBYTASK_CLIENTEND_PENDING = 25,
  LOBBYTASK_CLIENTEND_DISCONNECT = 26,
  LOBBYTASK_CLIENTEND_COOLOFF = 27,
  LOBBYTASK_CLIENTEND_SHUTDOWN = 28,
  LOBBYTASK_HOSTLAUNCH_INIT = 29,
  LOBBYTASK_HOSTLAUNCH_PUMP = 30,
  LOBBYTASK_HOSTLAUNCH_PRELOAD = 31,
  LOBBYTASK_HOSTLAUNCH_GO = 32,
  LOBBYTASK_CLIENTLAUNCH_INIT = 33,
  LOBBYTASK_CLIENTLAUNCH_PUMP = 34,
  LOBBYTASK_CLIENTLAUNCH_GO = 35,
  LOBBYTASK_SUCCESS = 36,
  LOBBYTASK_FAILURE = 37,
};
enum class dvarType_t : int32_t {
  DVAR_TYPE_INVALID = 0,
  DVAR_TYPE_BOOL = 1,
  DVAR_TYPE_FLOAT = 2,
  DVAR_TYPE_FLOAT_2 = 3,
  DVAR_TYPE_FLOAT_3 = 4,
  DVAR_TYPE_FLOAT_4 = 5,
  DVAR_TYPE_INT = 6,
  DVAR_TYPE_ENUM = 7,
  DVAR_TYPE_STRING = 8,
  DVAR_TYPE_COLOR = 9,
  DVAR_TYPE_INT64 = 10,
  DVAR_TYPE_UINT64 = 11,
  DVAR_TYPE_LINEAR_COLOR_RGB = 12,
  DVAR_TYPE_COLOR_XYZ = 13,
  DVAR_TYPE_COLOR_LAB = 14,
  DVAR_TYPE_SESSIONMODE_BASE_DVAR = 15,
  DVAR_TYPE_COUNT = 16,
};
enum class UIVisibilityBit : int32_t {
  BIT_HUD_VISIBLE = 0,
  BIT_WEAPON_HUD_VISIBLE = 1,
  BIT_G_COMPASS_SHOW_ENEMIES = 2,
  BIT_RADAR_CLIENT = 3,
  BIT_NEMESIS_KILLCAM = 4,
  UI_CLIENT_HIGHEST_VISIBILITY_BIT = 4,
  BIT_FINAL_KILLCAM = 5,
  BIT_ROUND_END_KILLCAM = 6,
  BIT_RADAR_ALLIES = 7,
  BIT_RADAR_AXIS = 8,
  BIT_ENABLE_POPUPS = 9,
  BIT_BOMB_TIMER = 10,
  BIT_BOMB_TIMER_A = 11,
  BIT_BOMB_TIMER_B = 12,
  BIT_AMMO_COUNTER_HIDE = 13,
  BIT_HUD_HARDCORE = 14,
  BIT_DRAW_SPECTATOR_MESSAGES = 15,
  BIT_DISABLE_INGAME_MENU = 16,
  BIT_GAME_ENDED = 17,
  BIT_OVERTIME = 18,
  UI_CLIENT_AND_MATCH_HIGHEST_VISIBILITY_BIT = 18,
  BIT_DEMO_CAMERA_MODE_THIRDPERSON = 19,
  BIT_DEMO_CAMERA_MODE_MOVIECAM = 20,
  BIT_DEMO_ALL_GAME_HUD_HIDDEN = 21,
  BIT_DEMO_HUD_HIDDEN = 22,
  BIT_IN_KILLCAM = 23,
  BIT_SELECTING_LOCATION = 24,
  BIT_IS_FLASH_BANGED = 25,
  BIT_UI_ACTIVE = 26,
  BIT_SPECTATING_CLIENT = 27,
  BIT_IS_SCOPED = 28,
  BIT_IN_VEHICLE = 29,
  BIT_IN_GUIDED_MISSILE = 30,
  BIT_IS_FUEL_WEAPON = 31,
  BIT_SELECTING_LOCATIONAL_KILLSTREAK = 32,
  BIT_IS_DEMO_PLAYING = 33,
  BIT_IS_DEMO_MOVIE_RENDERING = 34,
  BIT_ADS_JAVELIN = 35,
  BIT_EXTRACAM_ON = 36,
  BIT_EXTRACAM_ACTIVE = 37,
  BIT_EXTRACAM_STATIC = 38,
  BIT_TEAM_FREE = 39,
  BIT_TEAM_ALLIES = 40,
  BIT_TEAM_AXIS = 41,
  BIT_TEAM_SPECTATOR = 42,
  BIT_COMPASS_VISIBLE = 43,
  BIT_HUD_SHOWOBJICONS = 44,
  BIT_SCOREBOARD_OPEN = 45,
  BIT_POPUPS_VISIBLE = 46,
  BIT_HUD_OBITUARIES = 47,
  BIT_POF_SPEC_ALLOW_FREELOOK = 48,
  BIT_POF_FOLLOW = 49,
  BIT_IN_REMOTE_KILLSTREAK_STATIC = 50,
  BIT_EMP_ACTIVE = 51,
  BIT_TOTAL_COVERAGE_ACTIVE = 52,
  BIT_COUNTER_UAV_ACTIVE = 53,
  BIT_IS_THIRD_PERSON = 54,
  BIT_PLAYER_DEAD = 55,
  BIT_IN_REMOTE_MISSILE = 56,
  BIT_IS_PLAYER_ZOMBIE = 57,
  BIT_IS_PLAYER_IN_AFTERLIFE = 58,
  BIT_CAMERA_ANIM_HIDING_HUD = 59,
  BIT_MIGRATING_HOST = 60,
  BIT_HIDE_FOR_FULLSCREEN_MENU = 61,
  BIT_DRAW_RETICLE = 62,
  UI_VISIBILITY_BIT_COUNT = 63,
};
enum class ObjectiveTypes : int32_t {
  OBJECTIVE_TYPE_INVALID = -1,
  OBJECTIVE_TYPE_WAYPOINT = 0,
  OBJECTIVE_TYPE_3DPROMPT = 1,
  OBJECTIVE_TYPE_NOINDICATOR = 2,
  OBJECTIVE_TYPE_WOUNDED_SOLDIER = 3,
  OBJECTIVE_TYPE_COUNT = 4,
};
enum class WeaponFireEvent : int32_t {
  WEAPON_EVENT_CHANGE = 0,
  WEAPON_EVENT_FIRING = 1,
  WEAPON_EVENT_FIRED = 2,
  WEAPON_EVENT_CANCELLED = 3,
};
enum class WoundedSoldierType : int32_t {
  WOUNDED_SOLDIER_TYPE_MINOR = 0,
  WOUNDED_SOLDIER_TYPE_MEDIUM = 1,
  WOUNDED_SOLDIER_TYPE_SEVERE = 2,
  WOUNDED_SOLDIER_TYPE_CRITICAL = 3,
  WOUNDED_SOLDIER_TYPE_COUNT = 4,
};
enum class RocketLauncherTargetStatesFlags : int32_t {
  ROCKET_LAUNCHER_TARGET_FOUND = 0,
  ROCKET_LAUNCHER_TARGET_LOCKING = 1,
  ROCKET_LAUNCHER_TARGET_LOCKED = 2,
  ROCKET_LAUNCHER_TARGET_OUT_OF_RANGE = 3,
};
enum class BleedOutStateFlags : int32_t {
  BLEEDOUT_STATE_FLAG_BLEEDING_OUT = 0,
  BLEEDOUT_STATE_FLAG_BEING_REVIVED = 1,
  BLEEDOUT_STATE_FLAG_CLAMPED = 2,
};
enum class VehiclePartDestroyed : int32_t {
  VEHICLE_PART_DESTROYED_1 = 0,
  VEHICLE_PART_DESTROYED_2 = 1,
  VEHICLE_PART_DESTROYED_COUNT = 2,
};
enum class MissileLockedOnDirection : int32_t {
  MISSILE_LOCKED_ON_DIRECTION_CENTER = 0,
  MISSILE_LOCKED_ON_DIRECTION_UP = 1,
  MISSILE_LOCKED_ON_DIRECTION_DOWN = 2,
  MISSILE_LOCKED_ON_DIRECTION_LEFT = 3,
  MISSILE_LOCKED_ON_DIRECTION_RIGHT = 4,
  MISSILE_LOCKED_ON_DIRECTION_COUNT = 5,
};
enum class VehicleFullscreenFilter : int32_t {
  VEHICLE_FULLSCREEN_FILTER_NONE = 0,
  VEHICLE_FULLSCREEN_FILTER_INFRARED = 1,
  VEHICLE_FULLSCREEN_FILTER_FLIR = 2,
};
enum class WeakpointWidgetStates : int32_t {
  WEAKPOINT_STATE_DEFAULT = 0,
  WEAKPOINT_STATE_CLOSE = 1,
  WEAKPOINT_STATE_MEDIUM = 2,
  WEAKPOINT_STATE_FAR = 3,
  WEAKPOINT_STATE_OBSCURED = 4,
  WEAKPOINT_STATE_HIDDEN = 5,
  WEAKPOINT_STATE_CLOSING = 6,
};
enum class EnemyTargetStates : int32_t {
  ENEMY_TARGET_NONE = 0,
  ENEMY_TARGET_LOCKED = 1,
  ENEMY_TARGET_OUT_OF_RANGE = 2,
};
enum class LUIAlignment : int32_t {
  LUI_ALIGNMENT_NONE = 0,
  LUI_ALIGNMENT_LEFT = 1,
  LUI_ALIGNMENT_CENTER = 2,
  LUI_ALIGNMENT_RIGHT = 4,
  LUI_ALIGNMENT_TOP = 8,
  LUI_ALIGNMENT_MIDDLE = 16,
  LUI_ALIGNMENT_BOTTOM = 32,
  LUI_ALIGNMENT_SCREEN_SPACE = 64,
  LUI_ALIGNMENT_HORIZONTAL_MASK = 7,
  LUI_ALIGNMENT_VERTICAL_MASK = 56,
};
enum class UIModelClientFieldType : int32_t {
  CF_INT = 0,
  CF_FLOAT = 1,
  CF_COUNTER = 2,
};
enum class ArmbladeLockState : int32_t {
  ARMBLADE_STATE_NONE = 0,
  ARMBLADE_TARGETTED = 1,
  ARMBLADE_ATTACKING = 2,
};
enum class SettingTeamIndicator : int32_t {
  SettingTeamIndicator_FULL = 0,
  SettingTeamIndicator_ABBREVIATED = 1,
  SettingTeamIndicator_ICON = 2,
  SettingTeamIndicator_COUNT = 3,
};
enum class DamageFeedbackState : int32_t {
  DAMAGE_FEEDBACK_STATE_NONE = 0,
  DAMAGE_FEEDBACK_STATE_1 = 1,
  DAMAGE_FEEDBACK_STATE_2 = 2,
  DAMAGE_FEEDBACK_STATE_3 = 3,
  DAMAGE_FEEDBACK_STATE_4 = 4,
  DAMAGE_FEEDBACK_STATE_5 = 5,
  DAMAGE_FEEDBACK_STATE_COUNT = 6,
  DAMAGE_FEEDBACK_STATE_IGNORE = 6,
  DAMAGE_FEEDBACK_STATE_NEXT_UNUSED_BIT = 4,
  DAMAGE_FEEDBACK_STATE_MASK = 7,
};
enum class DamageFeedbackFlags : int32_t {
  DAMAGE_FEEDBACK_FLAG_FLAK = 0,
  DAMAGE_FEEDBACK_FLAG_TAC_MASK = 1,
  DAMAGE_FEEDBACK_FLAG_ARMOR = 2,
  DAMAGE_FEEDBACK_FLAG_DEAD = 3,
};
enum class ColorVisionDeficiencies : int32_t {
  CVD_OFF = 0,
  CVD_DEUTERANOMALY = 1,
  CVD_PROTANOMALY = 2,
  CVD_TRITANOMALY = 3,
  CVD_COUNT = 4,
};
enum class HlsChannelState_e : int32_t {
  HLS_CHANNEL_STATE_LIVE = 0,
  HLS_CHANNEL_STATE_REPLAY = 1,
  HLS_CHANNEL_STATE_OFFLINE = 2,
  HLS_CHANNEL_STATE_NOT_FOUND = 3,
};
enum class LMGInfiniteState : int32_t {
  LMG_INFINITE_STATE_PRINTING = 0,
  LMG_INFINITE_STATE_FIRING = 1,
  LMG_INFINITE_STATE_FULL = 2,
  LMG_INFINITE_STATE_EMPTY = 3,
};
enum class CompassType : int32_t {
  COMPASS_TYPE_PARTIAL = 0,
  COMPASS_TYPE_FULL = 1,
  COMPASS_TYPE_PARTIAL_WORLDALIGNED = 2,
};
enum class bunkCollectibleSizes_e : int32_t {
  COLLECTIBLE_SIZE_SMALL = 0,
  COLLECTIBLE_SIZE_MEDIUM = 1,
  COLLECTIBLE_SIZE_LARGE = 2,
  COLLECTIBLE_SIZE_COUNT = 3,
};
enum class KeyboardType : int32_t {
  KEYBOARD_TYPE_NONE = 0,
  KEYBOARD_TYPE_DEMO = 1,
  KEYBOARD_TYPE_EMAIL = 2,
  KEYBOARD_TYPE_CUSTOM_CLASS = 3,
  KEYBOARD_TYPE_CLASS_SET = 4,
  KEYBOARD_TYPE_BUBBLEGUM_PACK = 5,
  KEYBOARD_TYPE_LEAGUES = 6,
  KEYBOARD_TYPE_TWITCH_USER = 7,
  KEYBOARD_TYPE_TWITCH_PASS = 8,
  KEYBOARD_TYPE_TEXT_MESSAGE = 9,
  KEYBOARD_TYPE_ADD_FRIEND = 10,
  KEYBOARD_TYPE_REGISTRATION_INPUT_PASSWORD = 11,
  KEYBOARD_TYPE_REGISTRATION_INPUT_ACCENTS = 12,
  KEYBOARD_TYPE_REGISTRATION_INPUT_NUMERIC = 13,
  KEYBOARD_TYPE_REGISTRATION_INPUT_ACCOUNTNAME = 14,
  KEYBOARD_TYPE_NUMERIC_FIELD = 15,
  KEYBOARD_TYPE_CLAN_TAG = 16,
  KEYBOARD_TYPE_TWITTER_USER = 17,
  KEYBOARD_TYPE_TWITTER_PASS = 18,
  KEYBOARD_TYPE_PASSWORD = 19,
  KEYBOARD_TYPE_REGISTER_FIRST_NAME = 20,
  KEYBOARD_TYPE_REGISTER_LAST_NAME = 21,
  KEYBOARD_TYPE_REGISTER_ZIP_CODE = 22,
  KEYBOARD_TYPE_REGISTER_USERNAME = 23,
  KEYBOARD_TYPE_REGISTER_EMAIL = 24,
  KEYBOARD_TYPE_REGISTER_PASSWORD = 25,
  KEYBOARD_TYPE_CONFIRM_PASSWORD = 26,
  KEYBOARD_TYPE_FILESHARE_DOWNLOAD_NAME = 27,
  KEYBOARD_TYPE_FILESHARE_PUBLISH_NAME = 28,
  KEYBOARD_TYPE_FILESHARE_PUBLISH_DESCRIPTION = 29,
  KEYBOARD_TYPE_FILESHARE_PUBLISH_TAGS = 30,
  KEYBOARD_TYPE_GUNSMITH = 31,
  KEYBOARD_TYPE_EMBLEMS = 32,
  KEYBOARD_TYPE_PAINTJOB = 33,
  KEYBOARD_TYPE_TOTP = 34,
  KEYBOARD_TYPE_TEAM_IDENTITY_TEAMNAME = 35,
  KEYBOARD_TYPE_SERVER_NAME = 36,
  KEYBOARD_TYPE_SERVER_DESCRIPTION = 37,
  KEYBOARD_TYPE_SERVER_PASSWORD = 38,
  KEYBOARD_TYPE_SERVER_CLIENT_PASSWORD = 39,
  KEYBOARD_TYPE_SERVER_FILTER_KEYWORDS = 40,
  KEYBOARD_TYPE_COUNT = 41,
};
enum class LbFilter : int32_t {
  LB_FILTER_NONE = 0,
  LB_FILTER_FRIENDS = 1,
  LB_FILTER_LOBBY_MEMBERS = 2,
  LB_FILTER_CUSTOM = 3,
  LB_FILTER_COUNT = 4,
};
enum class Limit : int32_t {
  LIMIT_INT_MAX = 0,
  LIMIT_UINT_MAX = 1,
  LIMIT_INT64_MAX = 2,
  LIMIT_UINT64_MAX = 3,
};
enum class LbTrackType : int32_t {
  LB_TRK_ALLTIME = 0,
  LB_TRK_WEEKLY = 1,
  LB_TRK_MONTHLY = 2,
  LB_TRK_PRESTIGE_ALLTIME = 3,
  LB_TRK_PRESTIGE_WEEKLY = 4,
  LB_TRK_PRESTIGE_MONTHLY = 5,
  LB_TRK_DAILY = 6,
  LB_TRK_PRESTIGE_DAILY = 7,
  LB_TRK_COUNT = 8,
};
enum class StoreProductPurchaseStatus : int32_t {
  STORE_PRODUCT_NOT_PURCHASED = 0,
  STORE_PRODUCT_PURCHASED = 1,
};
enum class CustomizationType : int32_t {
  CUSTOMIZATION_TYPE_PAINTSHOP_VIEW_LEFT = 0,
  CUSTOMIZATION_TYPE_PAINTSHOP_VIEW_TOP = 1,
  CUSTOMIZATION_TYPE_PAINTSHOP_VIEW_RIGHT = 2,
  CUSTOMIZATION_TYPE_EMBLEM = 3,
  CUSTOMIZATION_TYPE_COUNT = 4,
};
enum class CustomizationScaleType : int32_t {
  CUSTOMIZATION_SCALE_TYPE_FIXED = 0,
  CUSTOMIZATION_SCALE_TYPE_FREE = 1,
};
enum class CustomizationTypeLayerCount : int32_t {
  CUSTOMIZATION_TYPE_EMBLEM_MAX_LAYERS = 64,
  CUSTOMIZATION_TYPE_PAINTSHOP_MAX_LAYERS = 64,
};
enum class CustomizationPaintjobInvalidID : int32_t {
  CUSTOMIZATION_INVALID_PAINTJOB_INDEX = 15,
  CUSTOMIZATION_INVALID_PAINTJOB_SLOT = 15,
};
enum class CustomizationTypeGroupCount : int32_t {
  CUSTOMIZATION_TYPE_MAX_GROUPS = 11,
};
enum class CustomizationColorSwatch : int32_t {
  CUSTOMIZATION_COLOR_SWATCH_ROWS = 9,
  CUSTOMIZATION_COLOR_SWATCH_COLUMNS = 13,
};
enum class CustomizationEditorMode : int32_t {
  CUSTOMIZATION_EDITOR_MODE_BROWSE = 0,
  CUSTOMIZATION_EDITOR_MODE_EDIT = 1,
  CUSTOMIZATION_EDITOR_MODE_NONE = 2,
  CUSTOMIZATION_EDITOR_MODE_COUNT = 3,
};
enum class CustomizationColorMode : int32_t {
  CUSTOMIZATION_COLOR_MODE_MIXER = 0,
  CUSTOMIZATION_COLOR_MODE_SOLID = 1,
  CUSTOMIZATION_COLOR_MODE_NONE = 2,
  CUSTOMIZATION_COLOR_MODE_COUNT = 3,
};
enum class CustomizationColorNum : int32_t {
  CUSTOMIZATION_COLOR_0 = 0,
  CUSTOMIZATION_COLOR_1 = 1,
  CUSTOMIZATION_COLOR_GRADIENT = 2,
  CUSTOMIZATION_COLOR_NONE = 3,
  CUSTOMIZATION_COLOR_COUNT = 4,
};
enum class CustomizationGradientType : int32_t {
  CUSTOMIZATION_GRADIENT_LINEAR = 0,
  CUSTOMIZATION_GRADIENT_RADIAL = 1,
  CUSTOMIZATION_GRADIENT_COUNT = 2,
};
enum class GunsmithMode : int32_t {
  GUNSMITHMODE_WEAPONLIST = 0,
  GUNSMITHMODE_VARIANTS = 1,
};
enum class PaintshopMode : int32_t {
  PAINTSHOPMODE_WEAPONLIST = 0,
  PAINTSHOPMODE_PAINTJOBS = 1,
};
enum class ShowcaseWeaponMode : int32_t {
  SHOWCASEWEAPON_WEAPONLIST = 0,
  SHOWCASEWEAPON_VARIANTS = 1,
};
enum class MessageDialogType : int32_t {
  MESSAGE_DIALOG_TYPE_INFO = 0,
  MESSAGE_DIALOG_TYPE_WARNING = 1,
  MESSAGE_DIALOG_TYPE_ERROR = 2,
  MESSAGE_DIALOG_TYPE_NOTICE = 3,
};
enum class eModes : int32_t {
  MODE_ZOMBIES = 0,
  MODE_MULTIPLAYER = 1,
  MODE_CAMPAIGN = 2,
  MODE_COUNT = 3,
  MODE_INVALID = 3,
  MODE_FIRST = 0,
};
enum class eGameModes : int32_t {
  MODE_GAME_MATCHMAKING_PLAYLIST = 0,
  MODE_GAME_MATCHMAKING_MANUAL = 1,
  MODE_GAME_DEFAULT = 2,
  MODE_GAME_LEAGUE = 3,
  MODE_GAME_FREERUN = 4,
  MODE_GAME_THEATER = 5,
  MODE_GAME_MANUAL_PLAYLIST = 6,
  MODE_GAME_RTS = 7,
  MODE_GAME_COUNT = 8,
  MODE_GAME_INVALID = 8,
};
enum class CACType : int32_t {
  CAC_TYPE_INVALID = -1,
  CAC_TYPE_MP_PUBLIC = 0,
  CAC_TYPE_MP_CUSTOM = 1,
  CAC_TYPE_MP_ARENA = 2,
  CAC_TYPE_MP_OFFLINE = 3,
  CAC_TYPE_FR = 4,
  CAC_TYPE_FR_OFFLINE = 5,
  CAC_TYPE_CP_ONLINE = 6,
  CAC_TYPE_CP_OFFLINE = 7,
  CAC_TYPE_ZM_ONLINE = 8,
  CAC_TYPE_ZM_OFFLINE = 9,
  CAC_TYPE_COUNT = 10,
};
enum class ClassSetType : int32_t {
  CLASS_SET_TYPE_INVALID = -1,
  CLASS_SET_TYPE_MP_PUBLIC = 0,
  CLASS_SET_TYPE_MP_CUSTOM = 1,
  CLASS_SET_TYPE_MP_ARENA = 2,
  CLASS_SET_TYPE_COUNT = 3,
};
enum class eGameType : int32_t {
  GAMETYPE_COOP = 0,
  GAMETYPE_DOA = 1,
  GAMETYPE_CPZM = 2,
  GAMETYPE_COUNT = 3,
  GAMETYPE_INVALID = 3,
};
enum class LobbyPregameState : int32_t {
  LOBBY_PREGAME_STATE_IDLE = 0,
  LOBBY_PREGAME_STATE_ITEM_VOTE = 1,
  LOBBY_PREGAME_STATE_CHARACTER_DRAFT = 2,
  LOBBY_PREGAME_STATE_CAC_EDIT = 3,
  LOBBY_PREGAME_STATE_SCORESTREAK_EDIT = 4,
  LOBBY_PREGAME_STATE_LAUNCH_GAME = 5,
  LOBBY_PREGAME_STATE_COUNT = 6,
};
enum class LobbyClientPregameState : int32_t {
  LOBBY_CLIENT_PREGAME_STATE_IDLE = 0,
  LOBBY_CLIENT_PREGAME_STATE_SELECTING = 1,
  LOBBY_CLIENT_PREGAME_STATE_SELECTED = 2,
  LOBBY_CLIENT_PREGAME_STATE_SELECTION_FORCED = 3,
  LOBBY_CLIENT_PREGAME_STATE_SELECTION_COMPLETE = 4,
  LOBBY_CLIENT_PREGAME_STATE_RESET = 5,
  LOBBY_CLIENT_PREGAME_STATE_END = 6,
  LOBBY_CLIENT_PREGAME_STATE_COUNT = 7,
};
enum class VoteType : int32_t {
  VOTE_TYPE_INVALID = 0,
  VOTE_TYPE_BAN = 1,
  VOTE_TYPE_PROTECT = 2,
  VOTE_TYPE_COUNT = 3,
};
enum class VoteItemType : int32_t {
  VOTE_ITEM_TYPE_INVALID = 0,
  VOTE_ITEM_TYPE_ITEM = 1,
  VOTE_ITEM_TYPE_ATTACHMENT = 2,
  VOTE_ITEM_TYPE_ITEM_ATTACHMENT = 3,
  VOTE_ITEM_TYPE_ATTACHMENT_GROUP = 4,
  VOTE_ITEM_TYPE_COUNT = 5,
};
enum class PregameSortType : int32_t {
  PREGAME_SORT_TYPE_RANDOM = 0,
  PREGAME_SORT_TYPE_CLIENTNUM = 1,
  PREGAME_SORT_TYPE_CODCASTER = 2,
  PREGAME_SORT_TYPE_COUNT = 3,
};
enum class PregameShuffleMethod : int32_t {
  PREGAME_SHUFFLE_METHOD_NONE = 0,
  PREGAME_SHUFFLE_METHOD_REVERSE = 1,
  PREGAME_SHUFFLE_METHOD_RANDOM = 2,
  PREGAME_SHUFFLE_METHOD_COUNT = 3,
};
enum class ItemRestrictionState : int32_t {
  ITEM_RESTRICTION_STATE_NONE = 0,
  ITEM_RESTRICTION_STATE_RESTRICTED = 1,
  ITEM_RESTRICTION_STATE_BANONLY = 2,
  ITEM_RESTRICTION_STATE_PROTECTED = 3,
};
enum class ProbationMode : int32_t {
  PROBATION_MODE_PUBLIC = 0,
  PROBATION_MODE_FIRST = 0,
  PROBATION_MODE_ARENA = 1,
  PROBATION_MODE_COUNT = 2,
};
enum class heroLoadoutTypes_e : int32_t {
  HERO_LOADOUT_TYPE_INVALID = -1,
  HERO_LOADOUT_TYPE_FIRST = 0,
  HERO_LOADOUT_TYPE_WEAPON = 0,
  HERO_LOADOUT_TYPE_GADGET = 1,
  HERO_LOADOUT_TYPE_COUNT = 2,
};
enum class HeroState : int32_t {
  HERO_STATE_CHARGING = 0,
  HERO_STATE_READY = 1,
  HERO_STATE_PRIMED = 2,
  HERO_STATE_ACTIVE = 3,
  HERO_STATE_FLICKERING = 4,
};
enum class eWeaponOptionGroup : int32_t {
  WEAPONOPTION_GROUP_FIRST = 0,
  WEAPONOPTION_GROUP_CAMO = 0,
  WEAPONOPTION_GROUP_TAG = 1,
  WEAPONOPTION_GROUP_EMBLEM = 2,
  WEAPONOPTION_GROUP_PAINTJOB = 3,
  WEAPONOPTION_GROUP_FIRST_ATTACHMENT_OPTION = 4,
  WEAPONOPTION_GROUP_RETICLE = 4,
  WEAPONOPTION_GROUP_LENS = 5,
  WEAPONOPTION_GROUP_RETICLE_COLOR = 6,
  WEAPONOPTION_GROUP_LAST_ATTACHMENT_OPTION = 6,
  WEAPONOPTION_GROUP_COUNT = 7,
  WEAPONOPTION_GROUP_INVALID = 7,
};
enum class itemGroup_t : int32_t {
  ITEMGROUP_SMG = 0,
  ITEMGROUP_FIRST = 0,
  ITEMGROUP_ASSAULT = 1,
  ITEMGROUP_CQB = 2,
  ITEMGROUP_LMG = 3,
  ITEMGROUP_SNIPER = 4,
  ITEMGROUP_PISTOL = 5,
  ITEMGROUP_LAUNCHER = 6,
  ITEMGROUP_KNIFE = 7,
  ITEMGROUP_SPECIAL = 8,
  ITEMGROUP_SHOTGUN = 9,
  ITEMGROUP_EXPLOSIVE = 10,
  ITEMGROUP_GRENADE = 11,
  ITEMGROUP_MASTERKEY = 12,
  ITEMGROUP_GRENADELAUNCHER = 13,
  ITEMGROUP_FLAMETHROWER = 14,
  ITEMGROUP_SPECIALTY = 15,
  ITEMGROUP_SPECIALGRENADE = 16,
  ITEMGROUP_MISCWEAPON = 17,
  ITEMGROUP_FEATURE = 18,
  ITEMGROUP_BONUSCARD = 19,
  ITEMGROUP_CYBERCOM_TACRIG = 20,
  ITEMGROUP_GLOBAL_ITEMS_START = 21,
  ITEMGROUP_KILLSTREAK = 21,
  ITEMGROUP_HERO = 22,
  ITEMGROUP_BUBBLEGUM = 23,
  ITEMGROUP_BUBBLEGUM_CONSUMABLE = 24,
  ITEMGROUP_CYBERCOM_CORE = 25,
  ITEMGROUP_CYBERCOM_ABILITIES = 26,
  ITEMGROUP_COUNT = 27,
  ITEMGROUP_INVALID = -1,
};
enum class prestigeTokenType_e : int32_t {
  PRESTIGE_TOKEN_RESPEC = 0,
  PRESTIGE_TOKEN_RESET_STATS = 1,
  PRESTIGE_TOKEN_EXTRA_CAC = 2,
  PRESTIGE_TOKEN_COUNT = 3,
};
enum class consoleLabel : int32_t {
  LABEL_DEFAULT = 0,
  LABEL_LIVE = 4,
  LABEL_LIVE_XBOX = 5,
  LABEL_LIVE_PS4 = 6,
  LABEL_LIVE_MATCHMAKING = 7,
  LABEL_DEMONWARE = 8,
  LABEL_LEADERBOARDS = 9,
  LABEL_LOBBY = 10,
  LABEL_LOBBYHOST = 11,
  LABEL_LOBBYCLIENT = 12,
  LABEL_LOBBYVM = 13,
  LABEL_MIGRATION = 14,
};
enum class errorCode : int32_t {
  ERROR_NONE = 0,
  ERROR_FATAL = 1,
  ERROR_DROP = 2,
  ERROR_FROM_STARTUP = 4,
  ERROR_SERVERDISCONNECT = 8,
  ERROR_DISCONNECT = 16,
  ERROR_SCRIPT = 32,
  ERROR_SCRIPT_DROP = 64,
  ERROR_LOCALIZATION = 128,
  ERROR_UI = 256,
  ERROR_LUA = 512,
  ERROR_SOFTRESTART = 1024,
  ERROR_SOFTRESTART_KEEPDW = 2048,
  ERROR_SOFTRESTART_SILENT = 4096,
};
enum class eVoipStatus : int32_t {
  VOIP_HIDDEN = 0,
  VOIP_TALKING = 1,
  VOIP_NOTTALKING = 2,
  VOIP_MUTED = 3,
  VOIP_ENEMY_TALKING = 4,
};
enum class objectiveState_t : int32_t {
  OBJST_EMPTY = 0,
  OBJST_ACTIVE = 1,
  OBJST_INVISIBLE = 2,
  OBJST_DONE = 3,
  OBJST_CURRENT = 4,
  OBJST_FAILED = 5,
  OBJST_NUMSTATES = 6,
};

enum class scoreBoardColumns_e : int32_t {
  SCOREBOARD_COLUMN_XUID = 0,
  SCOREBOARD_COLUMN_RANK_BG = 1,
  SCOREBOARD_COLUMN_RANK = 2,
  SCOREBOARD_COLUMN_RANK_ICON = 3,
  SCOREBOARD_COLUMN_NAME = 4,
  SCOREBOARD_COLUMN_1 = 5,
  SCOREBOARD_COLUMN_2 = 6,
  SCOREBOARD_COLUMN_3 = 7,
  SCOREBOARD_COLUMN_4 = 8,
  SCOREBOARD_COLUMN_5 = 9,
  SCOREBOARD_COLUMN_PING_BAR = 10,
  SCOREBOARD_COLUMN_CLIENTNUM = 11,
  SCOREBOARD_COLUMN_PING = 12,
};
enum class WeaponAttributesColumn : int32_t {
  WEAPONATTRIBUTES_GROUP = 0,
  WEAPONATTRIBUTES_REFERENCE = 1,
  WEAPONATTRIBUTES_ACCURACY = 2,
  WEAPONATTRIBUTES_DAMAGE = 3,
  WEAPONATTRIBUTES_RANGE = 4,
  WEAPONATTRIBUTES_FIRE_RATE = 5,
  WEAPONATTRIBUTES_MOBILITY = 6,
  WEAPONATTRIBUTES_MAG_SIZE = 7,
  WEAPONATTRIBUTES_FIRE_TYPE = 8,
  WEAPONATTRIBUTES_WEAPON_NAME = 9,
  WEAPONATTRIBUTES_COUNT = 10,
};
enum class attachmentTableColumn_e : int32_t {
  ATTACHMENTTABLE_COLUMN_INDEX = 0,
  ATTACHMENTTABLE_COLUMN_ATTACHPOINT = 1,
  ATTACHMENTTABLE_COLUMN_GROUP = 2,
  ATTACHMENTTABLE_COLUMN_NAME = 3,
  ATTACHMENTTABLE_COLUMN_REFERENCE = 4,
  ATTACHMENTTABLE_COLUMN_ITEM_COUNT = 5,
  ATTACHMENTTABLE_COLUMN_IMAGE = 6,
  ATTACHMENTTABLE_COLUMN_DESCRIPTION = 7,
  ATTACHMENTTABLE_COLUMN_CP_DESCRIPTION = 8,
  ATTACHMENTTABLE_COLUMN_DATA_STRING = 9,
  ATTACHMENTTABLE_COLUMN_DATA_INT = 10,
  ATTACHMENTTABLE_COLUMN_DATA_INT2 = 11,
  ATTACHMENTTABLE_COLUMN_COMPATIBLE_ATTACHMENTS = 12,
  ATTACHMENTTABLE_COLUMN_ALLOCATION = 13,
  ATTACHMENTTABLE_COLUMN_UNLOCK_LEVEL = 14,
  ATTACHMENTTABLE_COLUMN_UNLOCK_PLEVEL = 15,
  ATTACHMENTTABLE_COLUMN_BOT_PROBABILITY = 16,
  ATTACHMENTTABLE_COLUMN_DEFAULT_PRIMARY_CLASS = 17,
  ATTACHMENTTABLE_COLUMN_DEFAULT_SECONDARY_CLASS = 18,
  ATTACHMENTTABLE_COLUMN_ELITE = 19,
  ATTACHMENTTABLE_COLUMN_WEAPONOPTION_FILTER = 20,
  ATTACHMENTTABLE_COLUMN_ENTITLEMENT_NAME = 21,
  ATTACHMENTTABLE_COLUMN_SPECIAL_CONTRACT_INDEX = 22,
  ATTACHMENTTABLE_COLUMN_LIMITED_ITEM = 23,
  ATTACHMENTTABLE_COLUMN_COUNT = 24,
};
enum class KVSChannel : int32_t {
  MATCHMAKING_QOS = -1,
  CLIENT_STATS = -1,
};
enum class CustomGamesTaskUIState : int32_t {
  CUSTOMGAMES_TASK_UI_IDLE = 0,
  CUSTOMGAMES_TASK_UI_WORKING = 1,
  CUSTOMGAMES_TASK_UI_DONE = 2,
  CUSTOMGAMES_TASK_UI_ERROR = 3,
};
enum class fileShareLocation : int32_t {
  FILESHARE_LOCATION_INVALID = 0,
  FILESHARE_LOCATION_PUBLISHERSTORAGE = 1,
  FILESHARE_LOCATION_USERSTORAGE = 2,
  FILESHARE_LOCATION_POOLEDSTORAGE = 3,
};
enum class FileshareTaskUIState : int32_t {
  FILESHARE_TASK_UI_IDLE = 0,
  FILESHARE_TASK_UI_WORKING = 1,
  FILESHARE_TASK_UI_DONE = 2,
  FILESHARE_TASK_UI_ERROR = 3,
};
enum class FileshareFileCategory : int32_t {
  FILESHARE_INVALID = -1,
  FILESHARE_ALL = 0,
  FILESHARE_EMBLEM = 1,
  FILESHARE_PAINTJOB = 2,
  FILESHARE_VARIANT = 3,
};
enum class MediaType : int32_t {
  MEDIA_TYPE_FILESHARE = 0,
  MEDIA_TYPE_LOCAL = 1,
};
enum class FileshareCommunityDataType : int32_t {
  FILESHARE_COMMUNITY_DATA_INVALID = 0,
  FILESHARE_COMMUNITY_DATA_POPULAR = 1,
  FILESHARE_COMMUNITY_DATA_RECENT = 2,
  FILESHARE_COMMUNITY_DATA_TRENDING = 3,
  FILESHARE_COMMUNITY_DATA_RECENT_GAMES = 4,
};
enum class FileshareGroupsDataType : int32_t {
  FILESHARE_GROUPS_DATA_INVALID = 0,
  FILESHARE_GROUPS_DATA_RECENT = 1,
  FILESHARE_GROUPS_DATA_FAVORITE = 2,
  FILESHARE_GROUPS_DATA_FEATURED = 3,
};
enum class FileshareMode : int32_t {
  FILESHARE_MODE_USER = 0,
  FILESHARE_MODE_COMMUNITY = 1,
  FILESHARE_MODE_GROUPS = 2,
};
enum class ScreenshotViewType : int32_t {
  UI_SCREENSHOT_TYPE_SCREENSHOT = 0,
  UI_SCREENSHOT_TYPE_THUMBNAIL = 1,
  UI_SCREENSHOT_TYPE_MOTD = 2,
  UI_SCREENSHOT_TYPE_EMBLEM = 3,
  UI_SCREENSHOT_TYPE_COUNT = 4,
};
enum class ShoutcasterSettingsXray : int32_t {
  SHOUTCASTER_SETTING_XRAY_OFF = 0,
  SHOUTCASTER_SETTING_XRAY_ENEMY = 1,
  SHOUTCASTER_SETTING_XRAY_ALL = 2,
  SHOUTCASTER_SETTING_XRAY_COUNT = 3,
};
enum class ShoutcasterSettingShowPerks : int32_t {
  SHOUTCASTER_SETTING_SHOW_PERKS_OFF = 0,
  SHOUTCASTER_SETTING_SHOW_PERKS_ON = 1,
  SHOUTCASTER_SETTING_SHOW_PERKS_ALWAYS = 2,
  SHOUTCASTER_SETTING_SHOW_PERKS_STANDARD = 3,
  SHOUTCASTER_SETTING_SHOW_PERKS_COUNT = 4,
};
enum class ShoutcasterSettingMinimapMode : int32_t {
  SHOUTCASTER_SETTING_MINIMAP_MODE_OFF = 0,
  SHOUTCASTER_SETTING_MINIMAP_MODE_STANDARD = 1,
  SHOUTCASTER_SETTING_MINIMAP_MODE_FULL = 2,
  SHOUTCASTER_SETTING_MINIMAP_MODE_COUNT = 3,
};
enum class ShoutcasterSettingTeamIdentityMode : int32_t {
  SHOUTCASTER_SETTING_TEAM_IDENTITY_MODE_FACTION = 0,
  SHOUTCASTER_SETTING_TEAM_IDENTITY_MODE_CUSTOM = 1,
  SHOUTCASTER_SETTING_TEAM_IDENTITY_MODE_COUNT = 2,
};
enum class dlcIndex_t : int32_t {
  CONTENT_DEV_MAP_INDEX = -1,
  CONTENT_ORIGINAL_MAP_INDEX = 0,
  CONTENT_DLC0ZM_INDEX = 1,
  CONTENT_DLC0MP_INDEX = 2,
  CONTENT_DLC1_INDEX = 3,
  CONTENT_DLC2_INDEX = 4,
  CONTENT_DLC3_INDEX = 5,
  CONTENT_DLC4_INDEX = 6,
  CONTENT_DLC5_INDEX = 7,
  CONTENT_DLC1ZM_INDEX = 8,
  CONTENT_DLC2ZM_INDEX = 9,
  CONTENT_DLC3ZM_INDEX = 10,
  CONTENT_DLC4ZM_INDEX = 11,
  CONTENT_DLC6_INDEX = 12,
  CONTENT_DLCPC_INDEX = 13,
  CONTENT_DLC_INDEX_COUNT = 14,
  CONTENT_USERMAP_INDEX = 15,
};
enum class LUIButton : int32_t {
  LUI_KEY_NONE = 0,
  LUI_KEY_LEFT = 1,
  LUI_KEY_UP = 2,
  LUI_KEY_RIGHT = 3,
  LUI_KEY_DOWN = 4,
  LUI_KEY_XBA_PSCROSS = 5,
  LUI_KEY_XBB_PSCIRCLE = 6,
  LUI_KEY_XBX_PSSQUARE = 7,
  LUI_KEY_XBY_PSTRIANGLE = 8,
  LUI_KEY_BACK = 9,
  LUI_KEY_START = 10,
  LUI_KEY_LB = 11,
  LUI_KEY_RB = 12,
  LUI_KEY_LTRIG = 13,
  LUI_KEY_RTRIG = 14,
  LUI_KEY_LSTICK_PRESSED = 15,
  LUI_KEY_RSTICK_PRESSED = 16,
  LUI_KEY_PCKEY_MWHEELUP = 17,
  LUI_KEY_PCKEY_MWHEELDOWN = 18,
  LUI_KEY_PCKEY_0 = 19,
  LUI_KEY_PCKEY_1 = 20,
  LUI_KEY_PCKEY_2 = 21,
  LUI_BUTTON_COUNT = 22,
};
enum class LUIButtonFlags : int32_t {
  FLAG_DOWN = 1,
  FLAG_DPAD = 2,
  FLAG_ISREPEAT = 4,
};
enum class LUIButtonPromptStates : int32_t {
  FLAG_HIDE_PROMPTS = 0,
  FLAG_ENABLE_PROMPTS = 1,
  FLAG_DISABLE_PROMPTS = 2,
};
enum class gamepadType_e : int32_t {
  GAMEPAD_TYPE_ORBIS = 0,
  GAMEPAD_TYPE_DURANGO = 1,
  GAMEPAD_TYPE_STEAM = 2,
  GAMEPAD_TYPE_COUNT = 3,
};
enum class chatChannel_e : int32_t {
  CHAT_CHANNEL_ALL = 0,
  CHAT_CHANNEL_TEAM = 1,
  CHAT_CHANNEL_PARTY = 2,
  CHAT_CHANNEL_COUNT = 3,
};
enum class chatInGameState_e : int32_t {
  CHAT_INGAME_STATE_PLAYING = 0,
  CHAT_INGAME_STATE_SPECTATOR = 1,
  CHAT_INGAME_STATE_DEAD = 2,
  CHAT_INGAME_STATE_LOBBY = 3,
  CHAT_INGAME_STATE_COUNT = 4,
};
enum class HostServer : int32_t {
  HOST_SERVER_OK = 0,
  HOST_SERVER_BANDWIDTH_TEST_IN_PROGRESS = 1,
  HOST_SERVER_NOT_HOST_OF_PARTY = 2,
  HOST_SERVER_DEDICATED_ONLY = 3,
  HOST_SERVER_NAT_TYPE_NOT_ALLOWED = 4,
  HOST_SERVER_WE_SHOULD_NOT_HOST = 5,
  HOST_SERVER_IS_NOT_GOOD_CITIZEN = 6,
  HOST_SERVER_HAS_NOT_NECESSARY_BANDWIDTH = 7,
  HOST_SERVER_NET_ENGINE_NOT_STARTED = 8,
  HOST_SERVER_LIVE_STREAMING = 9,
  HOST_SERVER_BANNED_FROM_HOSTING = 10,
  HOST_NEVER_HOST_SERVER_DVAR = 11,
  HOST_SERVER_IS_IN_SHARE_PLAY = 12,
};
enum class StorageResult : int32_t {
  STORAGE_SUCCESS = 0,
  STORAGE_FAILURE_ERROR = 1,
  STORAGE_FAILURE_DDL = 2,
  STORAGE_FAILURE_NOTFOUND = 3,
};
enum class BuildIntField : int32_t {
  BUILD_INTFIELD_BUILD_NUMBER = 0,
  BUILD_INTFIELD_CHANGELIST = 1,
  BUILD_INTFIELD_INFO_VERSION = 2,
};
enum class BuildStringField : int32_t {
  BUILD_STRINGFIELD_MAJOR_VERSION = 0,
  BUILD_STRINGFIELD_MINOR_VERSION = 1,
  BUILD_STRINGFIELD_BUILD_ID = 2,
  BUILD_STRINGFIELD_BUILD_VERSION = 3,
  BUILD_STRINGFIELD_BUILD_MACHINE = 4,
  BUILD_STRINGFIELD_BUILD_TYPE = 5,
  BUILD_STRINGFIELD_BUILD_TIME = 6,
  BUILD_STRINGFIELD_BUILD_DISPLAY_NAME = 7,
  BUILD_STRINGFIELD_BUILD_NAME = 8,
  BUILD_STRINGFIELD_BUILD_BASE_NAME = 9,
  BUILD_STRINGFIELD_BUILD_CONFIG = 10,
  BUILD_STRINGFIELD_BUILD_MODE = 11,
  BUILD_STRINGFIELD_BUILD_PROJECT_NAME = 12,
  BUILD_STRINGFIELD_BUILD_LOCAL_CHANGES = 13,
  BUILD_STRINGFIELD_BUILD_INFO_NAME = 14,
  BUILD_STRINGFIELD_BUILD_INFO_SOURCE = 15,
  BUILD_STRINGFIELD_BUILD_INFO_STRING = 16,
};
enum class LiveMetPlayerUpdate : int32_t {
  LIVE_RECENTLY_MET_PLAYERS_UPDATE_INTERNAL = 0,
  LIVE_RECENTLY_MET_PLAYERS_UPDATE_RESET = 1,
  LIVE_RECENTLY_MET_PLAYERS_UPDATE_DOWNLOAD = 2,
  LIVE_RECENTLY_MET_PLAYERS_UPDATE_COUNT = 3,
};
enum class statsMilestoneTypes_t : int32_t {
  MILESTONE_GLOBAL = 0,
  MILESTONE_FIRST = 0,
  MILESTONE_WEAPON = 1,
  MILESTONE_GAMEMODE = 2,
  MILESTONE_GROUP = 3,
  MILESTONE_ATTACHMENTS = 4,
  MILESTONE_SPECIALIST = 5,
  MILESTONE_DAILY = 6,
  MILESTONE_COUNT = 7,
  MILESTONE_INVALID = 7,
};
enum class milestoneTableColumns_t : int32_t {
  MILESTONE_COLUMN_INDEX = 0,
  MILESTONE_COLUMN_TIERID = 1,
  MILESTONE_COLUMN_TARGETVALUE = 2,
  MILESTONE_COLUMN_STATTYPE = 3,
  MILESTONE_COLUMN_STATNAME = 4,
  MILESTONE_COLUMN_STRING = 5,
  MILESTONE_COLUMN_XPEARNED = 6,
  MILESTONE_COLUMN_PREREQUISITE = 7,
  MILESTONE_COLUMN_EXCLUDE = 8,
  MILESTONE_COLUMN_UNLOCKITEM = 9,
  MILESTONE_COLUMN_CHALLENGESTATNAME = 10,
  MILESTONE_COLUMN_UNLOCKLVL = 11,
  MILESTONE_COLUMN_UNLOCKIMAGE = 12,
  MILESTONE_COLUMN_INCLUDE = 13,
  MILESTONE_COLUMN_UNLOCKPLVL = 14,
  MILESTONE_COLUMN_RESETONPRESTIGE = 15,
  MILESTONE_COLUMN_CATEGORY = 16,
  MILESTONE_COLUMN_ISMAXLEVEL = 17,
  MILESTONE_COLUMN_ISMASTERY = 18,
  MILESTONE_COLUMN_ISITEMUNLOCKED = 19,
  MILESTONE_COLUMN_ISEXPERT = 20,
  MILESTONE_COLUMN_SETGLOBALSTAT = 21,
  MILESTONE_COLUMN_XPGROUPMASK = 22,
  MILESTONE_COLUMN_UNLOCKHEROITEM = 23,
  MILESTONE_COLUMN_VIALSEARNED = 24,
};
enum class PlatformPresenceFeatures : int32_t {
  PLATFORM_PRESENCE_FEATURES_NONE = 0,
  PLATFORM_PRESENCE_FEATURES_BASIC = 1,
  PLATFORM_PRESENCE_FEATURES_INTITLE = 2,
  PLATFORM_PRESENCE_FEATURES_EXTENDED_DW = 3,
  PLATFORM_PRESENCE_FEATURES_EXTENDED_PLATFORM = 4,
  PLATFORM_PRESENCE_FEATURES_COUNT = 5,
};
enum class InventoryCurrency : int32_t {
  INVENTORY_CURRENCY_INVALID = -1,
  INVENTORY_CURRENCY_COD_POINTS = 0,
  INVENTORY_CURRENCY_MP_LOOT_XP = 1,
  INVENTORY_CURRENCY_MP_CRYPTO_KEYS = 2,
  INVENTORY_CURRENCY_ZM_VIALS = 3,
  INVENTORY_CURRENCY_MP_BUNDLE_ITEM = 4,
  INVENTORY_CURRENCY_200CP_COMPENSATION = 5,
  INVENTORY_CURRENCY_1100CP_COMPENSATION = 6,
  INVENTORY_CURRENCY_2400CP_COMPENSATION = 7,
  INVENTORY_CURRENCY_5000CP_COMPENSATION = 8,
  INVENTORY_CURRENCY_13000CP_COMPENSATION = 9,
  INVENTORY_CURRENCY_CP_COMPENSATION = 10,
  INVENTORY_CURRENCY_RESERVE_2 = 11,
  INVENTORY_CURRENCY_RESERVE_3 = 12,
  INVENTORY_CURRENCY_RESERVE_4 = 13,
  INVENTORY_CURRENCY_RESERVE_5 = 14,
  INVENTORY_CURRENCY_COUNT = 15,
};
enum class LootCrateType : int32_t {
  LOOT_CRATE_TYPE_COMMON = 0,
  LOOT_CRATE_TYPE_RARE = 1,
  LOOT_CRATE_TYPE_BRIBE = 2,
  LOOT_CRATE_TYPE_COUNT = 3,
};
enum class WeaponOptionFilter : int32_t {
  WEAPONOPTION_FILTER_ZM = 0,
  WEAPONOPTION_FILTER_MP = 1,
  WEAPONOPTION_FILTER_CP = 2,
  WEAPONOPTION_FILTER_MODE_COUNT = 3,
  WEAPONOPTION_FILTER_BM = 3,
  WEAPONOPTION_FILTER_EXTRAS = 4,
  WEAPONOPTION_FILTER_COUNT = 5,
  WEAPONOPTION_FILTER_FIRST = 0,
};
enum class MultiplayerMusicTracks : int32_t {
  MP_MUSIC_TRACKS_NONE = 0,
  MP_MUSIC_TRACKS_DEFAULT = 1,
  MP_MUSIC_TRACKS_RANDOM = 2,
  MP_MUSIC_TRACKS_FIRST_TRACK = 3,
  MP_MUSIC_TRACKS_MAX = 64,
};
enum class MusicPlayerTableColumn : int32_t {
  MUSIC_PLAYER_COLUMN_INDEX = 0,
  MUSIC_PLAYER_COLUMN_ALIAS = 1,
  MUSIC_PLAYER_COLUMN_TITLE = 2,
  MUSIC_PLAYER_COLUMN_ARTIST = 3,
  MUSIC_PLAYER_COLUMN_ARTIST_2 = 4,
  MUSIC_PLAYER_COLUMN_FILTERS = 5,
};
enum class FrontendMusicTrackStates : int32_t {
  FRONTEND_MUSIC_STATE_DEFAULT = 0,
  FRONTEND_MUSIC_STATE_ON = 1,
  FRONTEND_MUSIC_STATE_OFF = 2,
  FRONTEND_MUSIC_STATE_COUNT = 3,
};
enum class InventoryPurchaseResult : int32_t {
  INVENTORY_PURCHASE_RESULT_INVALID = 0,
  INVENTORY_PURCHASE_RESULT_INPROGRESS = 1,
  INVENTORY_PURCHASE_RESULT_SUCCESS = 2,
  INVENTORY_PURCHASE_RESULT_FAILURE = 3,
};
enum class LootBurnDupeState : int32_t {
  LOOT_BURN_DUPE_IDLE = 0,
  LOOT_BURN_DUPE_REQUESTED = 1,
  LOOT_BURN_DUPE_BUSY = 2,
  LOOT_BURN_DUPE_DONE = 3,
  LOOT_BURN_DUPE_FAILED = 4,
};
enum class ContentFlagBits : int32_t {
  CONTENT_UNKNOWN = 1,
  CONTENT_ORIGINALMAPS = 2,
  CONTENT_DLC0ZM = 4,
  CONTENT_DLC0MP = 8,
  CONTENT_DLC1 = 16,
  CONTENT_DLC2 = 32,
  CONTENT_DLC3 = 64,
  CONTENT_DLC4 = 128,
  CONTENT_DLC5 = 256,
  CONTENT_DLC1ZM = 512,
  CONTENT_DLC2ZM = 1024,
  CONTENT_DLC3ZM = 2048,
  CONTENT_DLC4ZM = 4096,
  CONTENT_DLC6 = 0x2000,
  CONTENT_DLCPC = 0x4000,
};
enum class GPadButtonConfigs : int32_t {
  BUTTONS_DEFAULT = 0,
  BUTTONS_EXPERIMENTAL = 1,
  BUTTONS_LEFTY = 2,
  BUTTONS_NOMAD = 3,
  BUTTONS_CHARLIE = 4,
  BUTTONS_GUNSLINGER = 5,
  BUTTONS_BUMPERJUMPER = 6,
  BUTTONS_BUMPERTACTICAL = 7,
  BUTTONS_STICKMOVE = 8,
  BUTTON_CONFIG_COUNT = 9,
};
enum class LootRarityType : int32_t {
  LOOT_RARITY_TYPE_COMMON = 0,
  LOOT_RARITY_TYPE_RARE = 1,
  LOOT_RARITY_TYPE_LEGENDARY = 2,
  LOOT_RARITY_TYPE_EPIC = 3,
  LOOT_RARITY_TYPE_ZMCOMMON = 4,
  LOOT_RARITY_TYPE_ZMRARE = 5,
  LOOT_RARITY_TYPE_ZMULTRARARE = 6,
  LOOT_RARITY_TYPE_COUNT = 7,
};
enum class GPadStickConfigs : int32_t {
  THUMBSTICK_DEFAULT = 0,
  THUMBSTICK_SOUTHPAW = 1,
  THUMBSTICK_LEGACY = 2,
  THUMBSTICK_LEGACYSOUTHPAW = 3,
  THUMBSTICK_CONFIG_COUNT = 4,
};
enum class LootResultType : int32_t {
  LOOT_RESULT_INVALID = 0,
  LOOT_RESULT_SUCCESS = 1,
  LOOT_RESULT_FAILURE_INSUFFICIENT_FUNDS = 2,
  LOOT_RESULT_FAILURE_BAD_RESPONE = 3,
  LOOT_RESULT_FAILURE = 4,
  LOOT_RESULT_COUNT = 5,
};
enum class bunkCollectibleSlots_e : int32_t {
  BUNK_INVALID_SLOT = -1,
  BUNK_COLLECTIBLE_SMALL_1 = 0,
  BUNK_FIRST_SMALL_COLLECTIBLE = 0,
  BUNK_FIRST_COLLECTIBLE = 0,
  BUNK_COLLECTIBLE_SMALL_2 = 1,
  BUNK_COLLECTIBLE_SMALL_3 = 2,
  BUNK_COLLECTIBLE_SMALL_4 = 3,
  BUNK_COLLECTIBLE_SMALL_5 = 4,
  BUNK_COLLECTIBLE_SMALL_6 = 5,
  BUNK_LAST_SMALL_COLLECTIBLE = 5,
  BUNK_COLLECTIBLE_MEDIUM_1 = 6,
  BUNK_FIRST_MEDIUM_COLLECTIBLE = 6,
  BUNK_COLLECTIBLE_MEDIUM_2 = 7,
  BUNK_LAST_MEDIUM_COLLECTIBLE = 7,
  BUNK_COLLECTIBLE_LARGE_1 = 8,
  BUNK_FIRST_LARGE_COLLECTIBLE = 8,
  BUNK_LAST_LARGE_COLLECTIBLE = 8,
  BUNK_LAST_COLLECTIBLE = 8,
  BUNK_COLLECTIBLE_COUNT = 9,
};
enum class loadoutGadgetType_e : int32_t {
  LOADOUT_GADGETS_OFFHAND_PRIMARY = 0,
  LOADOUT_GADGETS_OFFHAND_SECONDARY = 1,
  LOADOUT_GADGETS_OFFHAND_SPECIAL = 2,
  LOADOUT_GADGETS_HERO_WEAPON = 3,
  LOADOUT_GADGETS_COUNT = 4,
};
enum class CharacterGenderTypes : int32_t {
  CHARACTER_GENDER_TYPE_MALE = 0,
  CHARACTER_GENDER_TYPE_MP = 0,
  CHARACTER_GENDER_TYPE_FIRST = 0,
  CHARACTER_GENDER_TYPE_FEMALE = 1,
  CHARACTER_GENDER_TYPE_COUNT = 2,
  CHARACTER_GENDER_TYPE_INVALID = 2,
  CHARACTER_GENDER_TYPE_ANY = 3,
};
enum class CharacterItemType : int32_t {
  CHARACTER_ITEM_TYPE_BODY = 0,
  CHARACTER_ITEM_TYPE_HELMET = 1,
  CHARACTER_ITEM_TYPE_COUNT = 2,
};
enum class team_t : int32_t {
  TEAM_FREE = 0,
  TEAM_BAD = 0,
  TEAM_DEAD = 0,
  TEAM_ALLIES = 1,
  TEAM_AXIS = 2,
  TEAM_THREE = 3,
  TEAM_FOUR = 4,
  TEAM_FIVE = 5,
  TEAM_SIX = 6,
  TEAM_SEVEN = 7,
  TEAM_EIGHT = 8,
  TEAM_NINE = 9,
  TEAM_TEN = 10,
  TEAM_ELEVEN = 11,
  TEAM_TWELVE = 12,
  TEAM_THIRTEEN = 13,
  TEAM_FOURTEEN = 14,
  TEAM_FIFTEEN = 15,
  TEAM_SIXTEEN = 16,
  TEAM_SEVENTEEN = 17,
  TEAM_EIGHTEEN = 18,
  TEAM_NEUTRAL = 19,
  TEAM_SPECTATOR = 20,
  TEAM_NUM_PLAYING_TEAMS = 20,
  TEAM_NUM_TEAMS = 21,
  TEAM_LOCALPLAYERS = 22,
  TEAM_FIRST_PLAYING_TEAM = 1,
  TEAM_LAST_PLAYING_TEAM = 19,
};
enum class CampaignMode : int32_t {
  CAMPAIGNMODE_DEFAULT = 0,
  CAMPAIGNMODE_ZOMBIES = 1,
  CAMPAIGNMODE_COUNT = 2,
  CAMPAIGNMODE_INVALID = 3,
};
enum class FeaturedCardType : int32_t {
  FEATURED_CARD_TYPE_NONE = 0,
  FEATURED_CARD_TYPE_REGULAR = 1,
  FEATURED_CARD_TYPE_GROUPS = 2,
  FEATURED_CARD_TYPE_CRM = 3,
  FEATURED_CARD_TYPE_MOTD = 4,
  FEATURED_CARD_TYPE_STORE = 5,
  FEATURED_CARD_TYPE_COUNT = 6,
};
enum class WaypointState : int32_t {
  WAYPOINT_STATE_DEFAULT = 0,
  WAYPOINT_STATE_OUT_OF_VIEWPORT = 1,
  WAYPOINT_STATE_LINE_OF_SIGHT = 2,
  WAYPOINT_STATE_OUT_OF_LINE_OF_SIGHT = 3,
  WAYPOINT_STATE_DISTANCE_CULLED = 4,
  WAYPOINT_STATE_COUNT = 5,
};
enum class CharacterGestureTypes : int32_t {
  GESTURE_TYPE_GOOD_GAME = 0,
  GESTURE_TYPE_THREATEN = 1,
  GESTURE_TYPE_BOAST = 2,
  GESTURE_TYPE_COUNT = 3,
};
enum class CharacterTauntTypes : int32_t {
  TAUNT_TYPE_FIRST_PLACE = 0,
  TAUNT_TYPE_COUNT = 1,
};

} // namespace lua
} // namespace ui
} // namespace game