// GENERATED by tools/gen_reloc_header.py - do not edit by hand.
//
// Exhaustive reference sets produced by tools/pe_xref.py, which scans the
// unpacked image byte by byte. A rip-relative reference cannot be missed by
// that method; Ghidra's analysis missed 112 of 377 once and cost this project
// a whole relocation.
#pragma once

#include <cstdint>
#include <cstddef>

namespace splitscreen {
struct reloc_ref {
  uint32_t insn_rva;   // start of the instruction
  uint8_t length;      // its total length
  uint8_t disp_offset; // where the 32-bit field sits inside it
  uint32_t target_rva; // what it currently points at
  bool rip_relative;   // true = displacement from insn end, false = ABS32
};

struct reloc_table {
  const char *name;
  uint32_t base_rva;
  uint32_t old_size;
  uint32_t new_size;
  const reloc_ref *refs;
  size_t count;
  // END-BOUND references. Some loops do not carry a count - they walk
  // `for (p = &array[0]; p < &array[N]; p++)` with BOTH addresses baked
  // in as immediates. Those refs must be rewritten to new_base +
  // NEW_SIZE, not shifted like the rest, or the array moves and every
  // loop still stops after the old number of elements.
  const reloc_ref *end_refs;
  size_t end_count;
};

// cg_fakeEntitiesInuseBitArray - PS4 bitarray<768>[4], [2] on PC. Slot 2 would
// clear 96 bytes of neighbouring globals. 33 references: 8 rip-relative + 25
// ABS32
inline constexpr reloc_ref bit_array_refs[] = {
    {0x000DE43C, 7, 3, 0x04C98B80, true},
    {0x000DE4E2, 7, 3, 0x04C98B80, true},
    {0x00843A8E, 7, 3, 0x04C98B80, true},
    {0x0085D28E, 7, 3, 0x04C98B80, true},
    {0x00CFD201, 7, 3, 0x04C98B80, true},
    {0x010612CD, 7, 3, 0x04C98B80, true},
    {0x01062B55, 7, 3, 0x04C98B80, true},
    {0x02CCE342, 7, 3, 0x04C98B80, true},
    {0x000F2F35, 7, 3, 0x04C98B80, false},
    {0x000F2FF7, 7, 3, 0x04C98B80, false},
    {0x000F9CC3, 8, 4, 0x04C98B80, false},
    {0x000F9D7A, 7, 3, 0x04C98B80, false},
    {0x0019AE48, 8, 4, 0x04C98B80, false},
    {0x004617BA, 8, 4, 0x04C98B80, false},
    {0x007039EB, 8, 4, 0x04C98B80, false},
    {0x00703A17, 8, 4, 0x04C98B80, false},
    {0x00703A3F, 7, 3, 0x04C98B80, false},
    {0x00703A6A, 8, 4, 0x04C98B80, false},
    {0x00703A96, 8, 4, 0x04C98B80, false},
    {0x00703AC2, 8, 4, 0x04C98B80, false},
    {0x00703B25, 8, 4, 0x04C98B80, false},
    {0x00703BC5, 7, 3, 0x04C98B80, false},
    {0x00760B81, 8, 4, 0x04C98B80, false},
    {0x00FFF4F2, 8, 4, 0x04C98B80, false},
    {0x00FFF513, 7, 3, 0x04C98B80, false},
    {0x01045DAC, 8, 4, 0x04C98B80, false},
    {0x01056CC8, 8, 4, 0x04C98B80, false},
    {0x01056CE5, 7, 3, 0x04C98B80, false},
    {0x0105D815, 8, 4, 0x04C98B80, false},
    {0x01062C45, 8, 4, 0x04C98B80, false},
    {0x011122AA, 7, 3, 0x04C98B80, false},
    {0x011122D8, 7, 3, 0x04C98B80, false},
};

// s_storage - PS4 Storage[4] (xuid, readOnLoginProcessed[4], StorageFile
// files[64] stride 0x220, StorageScratch at +0x8810). Slot 2 has no loadout
// buffer because AllocateMemory only ever ran for two controllers. 25
// references: 25 rip-relative + 0 ABS32
inline constexpr reloc_ref storage_refs[] = {
    {0x02218E37, 7, 3, 0x17897308, true}, {0x02218F8D, 7, 3, 0x1788EAC0, true},
    {0x0221903D, 7, 3, 0x1788EAC0, true}, {0x0221975D, 7, 3, 0x1788EAC0, true},
    {0x0221999B, 7, 3, 0x1788EAC0, true}, {0x02219A74, 7, 3, 0x1788EAC0, true},
    {0x02219C60, 7, 3, 0x1788EAC0, true}, {0x02219D1D, 7, 3, 0x1788EAC0, true},
    {0x02219D5F, 7, 3, 0x178972D0, true}, {0x02219FA7, 7, 3, 0x1788EAC0, true},
    {0x0221A093, 7, 3, 0x1788EAC0, true}, {0x0221A1C6, 7, 3, 0x1788EAC0, true},
    {0x0221A320, 7, 3, 0x1788EAC0, true}, {0x0221A3B7, 7, 3, 0x17897311, true},
    {0x0221A405, 7, 3, 0x1788EAC0, true}, {0x0221A495, 7, 3, 0x17897310, true},
    {0x0221A6B2, 7, 3, 0x1788EAC0, true}, {0x0221A83D, 7, 3, 0x1788EAC0, true},
    {0x0221A9BD, 7, 3, 0x1788EAC0, true}, {0x0221AA85, 7, 3, 0x1788EAC0, true},
    {0x0221AB22, 7, 3, 0x1788EAC0, true}, {0x0221AC70, 7, 3, 0x1788EAC0, true},
    {0x0221AE45, 7, 3, 0x1788EAC0, true}, {0x02EB3DE2, 7, 3, 0x1788EAC0, true},
    {0x02EFD197, 7, 3, 0x1788EAC0, true},
};

// per-client object pointer table, accessors at 0x01EC6DC0..0x01EC70E1.
// Dereferenced at +0x30 by the sign-in path; slot 2 read a float constant. 19
// references: 19 rip-relative + 0 ABS32
inline constexpr reloc_ref client_objs_refs[] = {
    {0x01EBA330, 7, 3, 0x03390190, true}, {0x01EBA343, 7, 3, 0x03390190, true},
    {0x01EBA373, 7, 3, 0x03390190, true}, {0x01EBA393, 7, 3, 0x03390190, true},
    {0x01EBA3D3, 7, 3, 0x03390190, true}, {0x01EBA3F3, 7, 3, 0x03390190, true},
    {0x01EBA403, 7, 3, 0x03390190, true}, {0x01EBA473, 7, 3, 0x03390190, true},
    {0x01EBA4A1, 7, 3, 0x03390190, true}, {0x01EBA513, 7, 3, 0x03390190, true},
    {0x01EBA533, 7, 3, 0x03390190, true}, {0x01EBA553, 7, 3, 0x03390190, true},
    {0x01EBA5A3, 7, 3, 0x03390190, true}, {0x01EBA5C3, 7, 3, 0x03390190, true},
    {0x01EBA5F5, 7, 3, 0x03390190, true}, {0x01EBA651, 7, 3, 0x03390190, true},
    {0x01EBA683, 7, 3, 0x03390190, true}, {0x01EBA6A8, 7, 3, 0x03390190, true},
    {0x01EBA6D3, 7, 3, 0x03390190, true},
};

// end-bound references for client_objs: rewritten to base + NEW size
inline constexpr reloc_ref client_objs_end_refs[] = {
    {0x01EBA34A, 7, 3, 0x033901A0, true},
    {0x01EBA39A, 7, 3, 0x033901A0, true},
    {0x01EBA6AF, 7, 3, 0x033901A0, true},
};

// userData_t[2] -> [4]. RE-ENABLED 2026-08-07. Measured at a fresh boot:
// controller 1 is already a signed-in secondary profile (+0x30 = 2) with
// storage and local-file stats readiness BEFORE it signs in, so a guest has to
// exist that way before Storage_Init. Run chain4 with BO3_OHNE=profile so it
// does not also move this table. 2 references: 2 rip-relative + 0 ABS32
inline constexpr reloc_ref client_ui_refs[] = {
    {0x02E900D2, 7, 3, 0x14F344B0, true},
    {0x02EFADE7, 7, 3, 0x14F344B0, true},
};

// per-local-client netchan/netstats records, stride 0x128, [2] -> [4]. This is
// what LobbyHost_AddLocalClients walks once its controller loop is widened past
// two; index 2 read past the end and faulted at 0x02173AD0. 15 references: 13
// rip-relative + 2 ABS32
inline constexpr reloc_ref netchan_refs[] = {
    {0x0211AFF2, 7, 3, 0x16DEAFD0, true}, {0x0211B5EE, 7, 3, 0x16DEAEB0, true},
    {0x0211B690, 7, 3, 0x16DEAF40, true}, {0x0211B697, 7, 3, 0x16DEAFD0, true},
    {0x0211B7BE, 7, 3, 0x16DEAF40, true}, {0x0211BB2D, 7, 3, 0x16DEAEB0, true},
    {0x0211BCE8, 7, 3, 0x16DEAEB0, true}, {0x0211BF51, 7, 3, 0x16DEAEB0, true},
    {0x0211C7E8, 7, 3, 0x16DEAF40, true}, {0x0211CA68, 7, 3, 0x16DEAEB0, false},
    {0x0211CEB3, 7, 3, 0x16DEAF40, true}, {0x0211D025, 7, 3, 0x16DEAFD0, false},
    {0x0211D35C, 7, 3, 0x16DEAEB0, true}, {0x0211D687, 7, 3, 0x16DEAF40, true},
    {0x0211E64E, 7, 3, 0x16DEAEB0, true},
};

// per-local-client object pointer table, lazily allocated 0x630 objects, [2] ->
// [4]. Faulting read at 0x029154E2 came from here. 28 references: 28
// rip-relative + 0 ABS32
inline constexpr reloc_ref objtab_a_refs[] = {
    {0x0144A5C9, 7, 3, 0x09B35878, true}, {0x0144A6B5, 7, 3, 0x09B35878, true},
    {0x0144A8AF, 7, 3, 0x09B35878, true}, {0x0144A957, 7, 3, 0x09B35878, true},
    {0x0144A9D7, 7, 3, 0x09B35878, true}, {0x0144AAC5, 7, 3, 0x09B35878, true},
    {0x0144AB77, 7, 3, 0x09B35878, true}, {0x0144ABE7, 7, 3, 0x09B35878, true},
    {0x0144AC67, 7, 3, 0x09B35878, true}, {0x0144ADD7, 7, 3, 0x09B35878, true},
    {0x0144B207, 7, 3, 0x09B35878, true}, {0x0144B287, 7, 3, 0x09B35878, true},
    {0x0144B307, 7, 3, 0x09B35878, true}, {0x0144B377, 7, 3, 0x09B35878, true},
    {0x0144B3F7, 7, 3, 0x09B35878, true}, {0x0144B477, 7, 3, 0x09B35878, true},
    {0x0144B4E7, 7, 3, 0x09B35878, true}, {0x0144B5C5, 7, 3, 0x09B35878, true},
    {0x0144B6C7, 7, 3, 0x09B35878, true}, {0x0144B737, 7, 3, 0x09B35878, true},
    {0x0144B807, 7, 3, 0x09B35878, true}, {0x0144B877, 7, 3, 0x09B35878, true},
    {0x0144B907, 7, 3, 0x09B35878, true}, {0x0144B977, 7, 3, 0x09B35878, true},
    {0x0144B9F7, 7, 3, 0x09B35878, true}, {0x0144BA67, 7, 3, 0x09B35878, true},
    {0x0144BAD7, 7, 3, 0x09B35878, true}, {0x0144BB47, 7, 3, 0x09B35878, true},
};

// per-local-client record table written by 0x0143A4E0 (array[i].field8 = i),
// [2] -> [4]. An out-of-range index WRITES here. 3 references: 3 rip-relative +
// 0 ABS32
inline constexpr reloc_ref objtab_b_refs[] = {
    {0x0143A58D, 7, 3, 0x09931F00, true},
    {0x02D39FCB, 7, 3, 0x09931F00, true},
    {0x02EF9C0C, 7, 3, 0x09931F00, true},
};

// the two globals behind cg_entitiesArray[2] on the PC, evicted so the array
// can be [4] in place. 0x70 = Com_AdjustMaxFPS record base (89 readers, writers
// 0x00843A48/0x00856EDB), 0x78 = one movups init. 92 references: 92
// rip-relative + 0 ABS32
inline constexpr reloc_ref fps_ctx_refs[] = {
    {0x001A44DC, 7, 3, 0x04C98B70, true}, {0x001A5EEA, 7, 3, 0x04C98B70, true},
    {0x001A81EB, 7, 3, 0x04C98B70, true}, {0x00470C6F, 7, 3, 0x04C98B70, true},
    {0x00472C42, 7, 3, 0x04C98B70, true}, {0x0047A8B5, 7, 3, 0x04C98B70, true},
    {0x0048503D, 7, 3, 0x04C98B70, true}, {0x00493263, 7, 3, 0x04C98B70, true},
    {0x004964A3, 7, 3, 0x04C98B70, true}, {0x00497F61, 7, 3, 0x04C98B70, true},
    {0x0049CB31, 7, 3, 0x04C98B70, true}, {0x004D7A22, 7, 3, 0x04C98B70, true},
    {0x00557603, 7, 3, 0x04C98B70, true}, {0x0061BDE8, 7, 3, 0x04C98B70, true},
    {0x006349D6, 7, 3, 0x04C98B70, true}, {0x006BEC9C, 7, 3, 0x04C98B70, true},
    {0x006C066F, 7, 3, 0x04C98B70, true}, {0x006C268C, 7, 3, 0x04C98B70, true},
    {0x006C406C, 7, 3, 0x04C98B70, true}, {0x006C75C5, 7, 3, 0x04C98B70, true},
    {0x006D3D55, 7, 3, 0x04C98B70, true}, {0x006F8809, 7, 3, 0x04C98B70, true},
    {0x0071B529, 7, 3, 0x04C98B70, true}, {0x00740309, 7, 3, 0x04C98B70, true},
    {0x0074F23C, 7, 3, 0x04C98B70, true}, {0x00763CDC, 7, 3, 0x04C98B70, true},
    {0x00843A48, 7, 3, 0x04C98B70, true}, {0x00853E27, 7, 3, 0x04C98B70, true},
    {0x00856EDB, 7, 3, 0x04C98B70, true}, {0x008C99D7, 7, 3, 0x04C98B70, true},
    {0x008DC4A5, 7, 3, 0x04C98B70, true}, {0x008EEEC4, 7, 3, 0x04C98B70, true},
    {0x008F9629, 7, 3, 0x04C98B70, true}, {0x008FAFDA, 7, 3, 0x04C98B70, true},
    {0x00901599, 7, 3, 0x04C98B70, true}, {0x00910765, 7, 3, 0x04C98B70, true},
    {0x0091213F, 7, 3, 0x04C98B70, true}, {0x00913B1D, 7, 3, 0x04C98B70, true},
    {0x00918C9D, 7, 3, 0x04C98B70, true}, {0x0092526C, 7, 3, 0x04C98B70, true},
    {0x0092B73E, 7, 3, 0x04C98B70, true}, {0x0094CEAF, 7, 3, 0x04C98B70, true},
    {0x0097B9F3, 7, 3, 0x04C98B70, true}, {0x00A1422F, 7, 3, 0x04C98B70, true},
    {0x00A4EA1E, 7, 3, 0x04C98B70, true}, {0x00A66295, 7, 3, 0x04C98B70, true},
    {0x00EA43E9, 7, 3, 0x04C98B70, true}, {0x00F2ECD8, 7, 3, 0x04C98B70, true},
    {0x00F45028, 7, 3, 0x04C98B70, true}, {0x00F4A122, 7, 3, 0x04C98B70, true},
    {0x00F4F2EF, 7, 3, 0x04C98B70, true}, {0x00F6B8C2, 7, 3, 0x04C98B70, true},
    {0x00F7223F, 7, 3, 0x04C98B70, true}, {0x00F7B609, 7, 3, 0x04C98B70, true},
    {0x00F7CFD5, 7, 3, 0x04C98B70, true}, {0x00F81B67, 7, 3, 0x04C98B70, true},
    {0x00F857C9, 7, 3, 0x04C98B70, true}, {0x00F88F13, 7, 3, 0x04C98B70, true},
    {0x00F8DA8F, 7, 3, 0x04C98B70, true}, {0x00F9AAB3, 7, 3, 0x04C98B70, true},
    {0x00FC3EA5, 7, 3, 0x04C98B70, true}, {0x00FF0C35, 7, 3, 0x04C98B70, true},
    {0x00FF7196, 7, 3, 0x04C98B70, true}, {0x01014D68, 7, 3, 0x04C98B70, true},
    {0x01019BCD, 7, 3, 0x04C98B70, true}, {0x0104DF40, 7, 3, 0x04C98B70, true},
    {0x0105F0AB, 7, 3, 0x04C98B70, true}, {0x010A06FF, 7, 3, 0x04C98B70, true},
    {0x010B15D5, 7, 3, 0x04C98B70, true}, {0x010B9B19, 7, 3, 0x04C98B70, true},
    {0x010F4E65, 7, 3, 0x04C98B70, true}, {0x01322417, 7, 3, 0x04C98B70, true},
    {0x01F1F7E6, 7, 3, 0x04C98B70, true}, {0x01F21B20, 7, 3, 0x04C98B70, true},
    {0x01F3A8E7, 7, 3, 0x04C98B70, true}, {0x01FBAF35, 7, 3, 0x04C98B70, true},
    {0x020021CB, 7, 3, 0x04C98B70, true}, {0x0259BCE9, 7, 3, 0x04C98B70, true},
    {0x025A62AC, 7, 3, 0x04C98B70, true}, {0x025BFDBC, 7, 3, 0x04C98B70, true},
    {0x025C2FA4, 7, 3, 0x04C98B70, true}, {0x02689F35, 7, 3, 0x04C98B70, true},
    {0x026D6A24, 7, 3, 0x04C98B70, true}, {0x026FD844, 7, 3, 0x04C98B70, true},
    {0x02735E5B, 7, 3, 0x04C98B70, true}, {0x0273906B, 7, 3, 0x04C98B70, true},
    {0x0274ED1B, 7, 3, 0x04C98B70, true}, {0x02765611, 7, 3, 0x04C98B70, true},
    {0x02768E8A, 7, 3, 0x04C98B70, true}, {0x0277BF8F, 7, 3, 0x04C98B70, true},
    {0x0278D7DA, 7, 3, 0x04C98B70, true}, {0x02CCE2D2, 7, 3, 0x04C98B78, true},
};

// cl_voiceCommunication - PS4 voiceCommunication_t[4] elem 0xA34, [2] on the
// PC, packed onto clientUIActives slot 2. Widened [2] -> [4]; the vacated
// original is zeroed by the component so clientUIActives[2] starts as the
// console's initial state. 12 references: 12 rip-relative + 0 ABS32
inline constexpr reloc_ref voice_comm_refs[] = {
    {0x013E3689, 7, 3, 0x0535BCB0, true}, {0x013E3808, 7, 3, 0x0535BCB0, true},
    {0x01EE9172, 7, 3, 0x0535BCB0, true}, {0x01EE943B, 7, 3, 0x0535BCB0, true},
    {0x013E385F, 7, 3, 0x0535BCB1, true}, {0x01359631, 7, 3, 0x0535C6D8, true},
    {0x013E3837, 6, 2, 0x0535C6D8, true}, {0x013E38AC, 7, 3, 0x0535C6D8, true},
    {0x013E38D6, 7, 3, 0x0535C6D8, true}, {0x013E38F1, 6, 2, 0x0535C6D8, true},
    {0x013E390C, 6, 2, 0x0535C6D8, true}, {0x013E3BD4, 7, 2, 0x0535C6D8, true},
};

// Cbuf per-local-client records, element 0x10, [2] on the PC. Slot 2 lands on a
// FOREIGN qword pointer global at 0x1689DF58 (11+ loads/stores). Read as the
// record's 'bytes used' dword those pointer bytes are large junk, so 0x020EC489
// `sub [rsi+0xC], ebx` UNDERFLOWS and 0x020EC48C movsxd sign-extends the
// negative result into a ~2 GB memcpy length - the 0xC0000005 at
// ext.dll+0x2F580 that was EVERY crash of 2026-08-18. Only 4 lea refs and no
// value loads/stores, so the array moves rather than the neighbour. [2] -> [4]
// zero-filled, which makes the engine's own `cmp [rsi+0xC], 0 / je` gate take
// its clean exit for an untouched client. 4 references: 4 rip-relative + 0
// ABS32
inline constexpr reloc_ref cbuf_refs[] = {
    {0x020DFBC8, 7, 3, 0x1681EFB8, true},
    {0x020E003A, 7, 3, 0x1681EFB8, true},
    {0x1CD91D25, 7, 3, 0x1681EFB8, true},
    {0x020DFEE1, 7, 3, 0x1681EFC0, true},
};

// playersKb - PS4 kbutton_t playersKb[4][47] (dwarf_localclient.txt line 172,
// element 0x18); [2] x 0x498 on the PC. Cleared per local client by
// CL_ClearKeys (PC 0x012F34D0, PS4 0x3DF980) from the tail of CL_Disconnect.
// Slot 2 lands on foreign globals - 11 lea + 264 loads/stores, 219 of them to a
// hot qword pointer at 0x052F3320 - and the memset at 0x012F34F5 is UNGUARDED,
// so it zeroes them before the /GS check at 0x012F34FA fires. [2] -> [4]. 213
// references: 95 rip-relative + 118 ABS32
inline constexpr reloc_ref players_kb_refs[] = {
    {0x012F327D, 7, 3, 0x052739F0, true},
    {0x012F34F9, 7, 3, 0x052739F0, true},
    {0x012F719B, 7, 3, 0x052739F0, true},
    {0x012F7224, 7, 3, 0x052739F0, true},
    {0x012F72AD, 7, 3, 0x052739F0, true},
    {0x012F72E9, 7, 3, 0x052739F0, true},
    {0x012F733F, 7, 3, 0x05273C60, true},
    {0x012F734B, 7, 3, 0x05273C60, true},
    {0x012F736E, 7, 3, 0x05273C78, true},
    {0x012F737A, 7, 3, 0x05273C78, true},
    {0x012F7402, 7, 3, 0x052739F0, true},
    {0x012F7482, 7, 3, 0x052739F0, true},
    {0x012F74FD, 7, 3, 0x05273CC0, true},
    {0x012F7570, 7, 3, 0x05273CC0, true},
    {0x012F7733, 7, 3, 0x052739F0, true},
    {0x012F77CE, 7, 3, 0x052739F0, true},
    {0x012F7809, 7, 3, 0x05273B58, true},
    {0x012F7815, 7, 3, 0x05273B58, true},
    {0x012F7835, 7, 3, 0x05273B70, true},
    {0x012F7841, 7, 3, 0x05273B70, true},
    {0x012F7864, 7, 3, 0x05273B40, true},
    {0x012F7870, 7, 3, 0x05273B40, true},
    {0x012F7893, 7, 3, 0x05273C00, true},
    {0x012F789F, 7, 3, 0x05273C00, true},
    {0x012F78C2, 7, 3, 0x05273D08, true},
    {0x012F78CE, 7, 3, 0x05273D08, true},
    {0x012F78F1, 7, 3, 0x05273D20, true},
    {0x012F78FD, 7, 3, 0x05273D20, true},
    {0x012F7920, 7, 3, 0x05273D38, true},
    {0x012F792C, 7, 3, 0x05273D38, true},
    {0x012F794F, 7, 3, 0x05273D50, true},
    {0x012F795B, 7, 3, 0x05273D50, true},
    {0x012F797E, 7, 3, 0x05273D68, true},
    {0x012F798A, 7, 3, 0x05273D68, true},
    {0x012F79AD, 7, 3, 0x05273D80, true},
    {0x012F79B9, 7, 3, 0x05273D80, true},
    {0x012F79DC, 7, 3, 0x05273DC8, true},
    {0x012F79E8, 7, 3, 0x05273DC8, true},
    {0x012F7A0B, 7, 3, 0x05273D98, true},
    {0x012F7A17, 7, 3, 0x05273D98, true},
    {0x012F7A3A, 7, 3, 0x05273DB0, true},
    {0x012F7A46, 7, 3, 0x05273DB0, true},
    {0x012F7A69, 7, 3, 0x05273A20, true},
    {0x012F7A75, 7, 3, 0x05273A20, true},
    {0x012F7A98, 7, 3, 0x05273A38, true},
    {0x012F7AA4, 7, 3, 0x05273A38, true},
    {0x012F7AC7, 7, 3, 0x05273A80, true},
    {0x012F7AD3, 7, 3, 0x05273A80, true},
    {0x012F7AF6, 7, 3, 0x05273A98, true},
    {0x012F7B02, 7, 3, 0x05273A98, true},
    {0x012F7B25, 7, 3, 0x05273AF8, true},
    {0x012F7B31, 7, 3, 0x05273AF8, true},
    {0x012F7B57, 7, 3, 0x052739F0, true},
    {0x012F7B7D, 7, 3, 0x052739F0, true},
    {0x012F7B9D, 7, 3, 0x05273A08, true},
    {0x012F7BA9, 7, 3, 0x05273A08, true},
    {0x012F7BCC, 7, 3, 0x05273A50, true},
    {0x012F7BD8, 7, 3, 0x05273A50, true},
    {0x012F7BFB, 7, 3, 0x05273A68, true},
    {0x012F7C07, 7, 3, 0x05273A68, true},
    {0x012F7C2A, 7, 3, 0x05273AB0, true},
    {0x012F7C36, 7, 3, 0x05273AB0, true},
    {0x012F7C59, 7, 3, 0x05273BA0, true},
    {0x012F7C65, 7, 3, 0x05273BA0, true},
    {0x012F7CD2, 7, 3, 0x05273C90, true},
    {0x012F7CDE, 7, 3, 0x05273C90, true},
    {0x012F7D04, 7, 3, 0x052739F0, true},
    {0x012F7D29, 7, 3, 0x052739F0, true},
    {0x012F7D58, 7, 3, 0x05273CF0, true},
    {0x012F7D61, 7, 3, 0x05273CF0, true},
    {0x012F7D84, 7, 3, 0x05273E70, true},
    {0x012F7DAA, 7, 3, 0x05273E70, true},
    {0x012F9E34, 7, 3, 0x052739F0, true},
    {0x012FF4E8, 7, 3, 0x052739F0, true},
    {0x012FFB64, 7, 3, 0x052739F0, true},
    {0x013000FB, 7, 3, 0x052739F0, true},
    {0x01300167, 7, 3, 0x052739F0, true},
    {0x01303A5D, 7, 3, 0x052739F0, true},
    {0x01308881, 7, 3, 0x05273BE8, true},
    {0x013088F3, 7, 3, 0x05273BE8, true},
    {0x0130899A, 7, 3, 0x052739F0, true},
    {0x01308A04, 7, 3, 0x052739F0, true},
    {0x01308AA6, 7, 3, 0x05273C18, true},
    {0x01308D41, 7, 3, 0x05273E40, true},
    {0x0131B3F3, 7, 3, 0x05273BB8, true},
    {0x0131B480, 7, 3, 0x05273E80, true},
    {0x0131B790, 7, 3, 0x05273C00, true},
    {0x0131B7F3, 7, 3, 0x05273C00, true},
    {0x0131B936, 7, 3, 0x05273C30, true},
    {0x0131BAA3, 7, 3, 0x05273BD0, true},
    {0x0131BB5E, 7, 3, 0x05273AC8, true},
    {0x0131BBAE, 7, 3, 0x05273AC8, true},
    {0x0131C124, 7, 3, 0x052739F0, true},
    {0x0131C1DF, 7, 3, 0x052739F0, true},
    {0x0131C2C6, 7, 3, 0x05273C48, true},
    {0x012F3754, 8, 4, 0x05273D1C, false},
    {0x01306C6A, 7, 3, 0x05273BC0, false},
    {0x01306C87, 7, 3, 0x05273BD8, false},
    {0x01308B80, 8, 4, 0x05273C18, false},
    {0x01308B8C, 8, 4, 0x05273C18, false},
    {0x01308B96, 8, 4, 0x05273C1C, false},
    {0x01308BA0, 8, 4, 0x05273C1C, false},
    {0x01308BAC, 8, 4, 0x05273C1C, false},
    {0x01308BB6, 8, 4, 0x05273C28, false},
    {0x01308BC2, 8, 4, 0x05273C20, false},
    {0x01308BCA, 8, 4, 0x05273C24, false},
    {0x01308BDC, 8, 4, 0x05273C24, false},
    {0x01308BE4, 8, 4, 0x05273C2C, false},
    {0x01308BEC, 8, 4, 0x05273C28, false},
    {0x01308BF4, 8, 4, 0x05273C2A, false},
    {0x01308D84, 8, 4, 0x05273B9C, false},
    {0x01308D8C, 8, 4, 0x05273B88, false},
    {0x01308D98, 8, 4, 0x05273B8C, false},
    {0x01308DA8, 8, 4, 0x05273B88, false},
    {0x01308DB6, 8, 4, 0x05273B8C, false},
    {0x01308DBE, 8, 4, 0x05273B98, false},
    {0x01308DC8, 8, 4, 0x05273B90, false},
    {0x0131B2B1, 8, 4, 0x05273B88, false},
    {0x0131B2BD, 8, 4, 0x05273B88, false},
    {0x0131B2C7, 8, 4, 0x05273B8C, false},
    {0x0131B2D1, 8, 4, 0x05273B8C, false},
    {0x0131B2DD, 8, 4, 0x05273B8C, false},
    {0x0131B2E7, 8, 4, 0x05273B98, false},
    {0x0131B2F7, 8, 4, 0x05273B90, false},
    {0x0131B305, 8, 4, 0x05273B94, false},
    {0x0131B30D, 8, 4, 0x05273B9C, false},
    {0x0131B315, 8, 4, 0x05273B98, false},
    {0x0131B31D, 8, 4, 0x05273B9A, false},
    {0x0131B325, 8, 4, 0x05273E40, false},
    {0x0131B331, 8, 4, 0x05273E40, false},
    {0x0131B33B, 8, 4, 0x05273E44, false},
    {0x0131B345, 8, 4, 0x05273E44, false},
    {0x0131B351, 8, 4, 0x05273E44, false},
    {0x0131B35B, 8, 4, 0x05273E50, false},
    {0x0131B368, 8, 4, 0x05273E48, false},
    {0x0131B370, 8, 4, 0x05273E4C, false},
    {0x0131B37C, 8, 4, 0x05273E4C, false},
    {0x0131B384, 8, 4, 0x05273E54, false},
    {0x0131B38C, 8, 4, 0x05273E50, false},
    {0x0131B394, 8, 4, 0x05273E52, false},
    {0x0131BA10, 8, 4, 0x05273C30, false},
    {0x0131BA1C, 8, 4, 0x05273C30, false},
    {0x0131BA26, 8, 4, 0x05273C34, false},
    {0x0131BA30, 8, 4, 0x05273C34, false},
    {0x0131BA3C, 8, 4, 0x05273C34, false},
    {0x0131BA46, 8, 4, 0x05273C40, false},
    {0x0131BA52, 8, 4, 0x05273C38, false},
    {0x0131BA5A, 8, 4, 0x05273C3C, false},
    {0x0131BA6C, 8, 4, 0x05273C3C, false},
    {0x0131BA74, 8, 4, 0x05273C44, false},
    {0x0131BA7C, 8, 4, 0x05273C40, false},
    {0x0131BA84, 8, 4, 0x05273C42, false},
    {0x0131BC24, 8, 4, 0x05273CEC, false},
    {0x0131BC2C, 8, 4, 0x05273CD8, false},
    {0x0131BC38, 8, 4, 0x05273CDC, false},
    {0x0131BC48, 8, 4, 0x05273CD8, false},
    {0x0131BC56, 8, 4, 0x05273CDC, false},
    {0x0131BC69, 8, 4, 0x05273CE0, false},
    {0x0131BC94, 8, 4, 0x05273B0C, false},
    {0x0131BC9C, 8, 4, 0x05273AF8, false},
    {0x0131BCAC, 8, 4, 0x05273AFC, false},
    {0x0131BCC0, 8, 4, 0x05273AF8, false},
    {0x0131BCD2, 8, 4, 0x05273AFC, false},
    {0x0131BCE9, 8, 4, 0x05273B00, false},
    {0x0131BE4F, 8, 4, 0x05273CD8, false},
    {0x0131BE5E, 8, 4, 0x05273CD8, false},
    {0x0131BE68, 8, 4, 0x05273CDC, false},
    {0x0131BE72, 8, 4, 0x05273CDC, false},
    {0x0131BE7E, 8, 4, 0x05273CDC, false},
    {0x0131BE88, 8, 4, 0x05273CE8, false},
    {0x0131BE98, 8, 4, 0x05273CE0, false},
    {0x0131BEAA, 8, 4, 0x05273CE4, false},
    {0x0131BEB2, 8, 4, 0x05273CEC, false},
    {0x0131BEBA, 8, 4, 0x05273CE8, false},
    {0x0131BEC2, 8, 4, 0x05273CEA, false},
    {0x0131BEE5, 8, 4, 0x05273AF8, false},
    {0x0131BEF7, 8, 4, 0x05273AF8, false},
    {0x0131BF01, 8, 4, 0x05273AFC, false},
    {0x0131BF0B, 8, 4, 0x05273AFC, false},
    {0x0131BF17, 8, 4, 0x05273AFC, false},
    {0x0131BF21, 8, 4, 0x05273B08, false},
    {0x0131BF2F, 8, 4, 0x05273B00, false},
    {0x0131BF3D, 8, 4, 0x05273B04, false},
    {0x0131BF45, 8, 4, 0x05273B0C, false},
    {0x0131BF4D, 8, 4, 0x05273B08, false},
    {0x0131BF55, 8, 4, 0x05273B0A, false},
    {0x0131BF5D, 8, 4, 0x05273DB0, false},
    {0x0131BF69, 8, 4, 0x05273DB0, false},
    {0x0131BF73, 8, 4, 0x05273DB4, false},
    {0x0131BF81, 8, 4, 0x05273DB4, false},
    {0x0131BF91, 8, 4, 0x05273DB4, false},
    {0x0131BF9F, 8, 4, 0x05273DC0, false},
    {0x0131BFAB, 8, 4, 0x05273DB8, false},
    {0x0131BFB3, 8, 4, 0x05273DBC, false},
    {0x0131BFBF, 8, 4, 0x05273DBC, false},
    {0x0131BFC7, 8, 4, 0x05273DC4, false},
    {0x0131BFCF, 8, 4, 0x05273DC0, false},
    {0x0131BFD7, 8, 4, 0x05273DC2, false},
    {0x0131BFE1, 8, 4, 0x05273CA0, false},
    {0x0131BFEB, 8, 4, 0x05273B08, false},
    {0x0131C0BA, 8, 4, 0x05273CD4, false},
    {0x0131C3A0, 8, 4, 0x05273C48, false},
    {0x0131C3AC, 8, 4, 0x05273C48, false},
    {0x0131C3B6, 8, 4, 0x05273C4C, false},
    {0x0131C3C0, 8, 4, 0x05273C4C, false},
    {0x0131C3CC, 8, 4, 0x05273C4C, false},
    {0x0131C3D6, 8, 4, 0x05273C58, false},
    {0x0131C3E2, 8, 4, 0x05273C50, false},
    {0x0131C3EA, 8, 4, 0x05273C54, false},
    {0x0131C3FC, 8, 4, 0x05273C54, false},
    {0x0131C404, 8, 4, 0x05273C5C, false},
    {0x0131C40C, 8, 4, 0x05273C58, false},
    {0x0131C414, 8, 4, 0x05273C5A, false},
};

// matchScoreBoardData - PS4 has four records; PC has two 0xDE8-byte records.
// CG_ResetScoreboard(2) otherwise starts at the adjacent command globals and
// zeroes CG_SetFocusScoreboardCmd_VAR's linked-list name, causing the
// repeatable round-load crash at 0x020ECCC3. [2] -> [4]. 70 references: 41
// rip-relative + 29 ABS32
inline constexpr reloc_ref match_scoreboard_refs[] = {
    {0x00A07A2C, 7, 3, 0x04C9F8F0, true},
    {0x00A07AE0, 7, 3, 0x04C9F8F0, true},
    {0x00A07B7D, 7, 3, 0x04C9F8F0, true},
    {0x00A09517, 7, 3, 0x04C9EC90, true},
    {0x00A0953D, 7, 3, 0x04C9EC90, true},
    {0x00A09556, 7, 3, 0x04C9EC90, true},
    {0x00A095AB, 7, 3, 0x04C9EC90, true},
    {0x00A095F6, 7, 3, 0x04C9ECB8, true},
    {0x00A09613, 7, 3, 0x04C9FA4C, true},
    {0x00A0966D, 7, 3, 0x04C9EC90, true},
    {0x00A0972D, 7, 3, 0x04C9EC90, true},
    {0x00A097D7, 7, 3, 0x04C9EC90, true},
    {0x00A098CA, 7, 3, 0x04C9F914, true},
    {0x00A09BD3, 7, 3, 0x04C9FA0C, true},
    {0x00A09BFB, 7, 3, 0x04C9EC90, true},
    {0x00A09C6B, 7, 3, 0x04C9EC90, true},
    {0x00A09CDB, 7, 3, 0x04C9EC90, true},
    {0x00A09D56, 7, 3, 0x04C9EC90, true},
    {0x00A09DCB, 7, 3, 0x04C9EC90, true},
    {0x00A09E4E, 7, 3, 0x04C9EC90, true},
    {0x00A09EC0, 7, 3, 0x04C9ECE0, true},
    {0x00A09EF3, 7, 3, 0x04C9FA70, true},
    {0x00A09F20, 7, 3, 0x04C9F928, true},
    {0x00A09F49, 7, 3, 0x04C9EC90, true},
    {0x00A09FDF, 7, 3, 0x04C9EC90, true},
    {0x00A0A11B, 7, 3, 0x04C9EC90, true},
    {0x00A0A173, 7, 3, 0x04C9FA74, true},
    {0x00A0A19D, 7, 3, 0x04C9EC90, true},
    {0x00A0D406, 7, 3, 0x04C9F8F0, true},
    {0x00A1057E, 7, 3, 0x04C9EC90, true},
    {0x00A105C2, 7, 3, 0x04C9EC90, true},
    {0x00A12126, 7, 3, 0x04C9EC90, true},
    {0x00A12265, 7, 3, 0x04C9EC90, true},
    {0x00A1241B, 7, 3, 0x04C9EC90, true},
    {0x00A126E9, 7, 3, 0x04C9EC90, true},
    {0x00A12769, 7, 3, 0x04C9EC90, true},
    {0x00A12879, 7, 3, 0x04C9EC90, true},
    {0x00A141AE, 7, 3, 0x04C9EC90, true},
    {0x00A15C44, 7, 3, 0x04C9EC90, true},
    {0x00A161D6, 7, 3, 0x04C9EC90, true},
    {0x00A181B9, 7, 3, 0x04C9ECE0, true},
    {0x00A099A2, 7, 3, 0x04C9ECE0, false},
    {0x00A099FD, 8, 4, 0x04C9EC90, false},
    {0x00A09A26, 8, 4, 0x04C9ECA4, false},
    {0x00A09A30, 8, 4, 0x04C9ECA0, false},
    {0x00A09A42, 8, 4, 0x04C9EC9C, false},
    {0x00A09A54, 8, 4, 0x04C9ECB0, false},
    {0x00A09AA1, 8, 4, 0x04C9EC90, false},
    {0x00A09AB3, 7, 3, 0x04C9ECB8, false},
    {0x00A09ACE, 7, 3, 0x04C9ECB8, false},
    {0x00A09ADA, 8, 4, 0x04C9F8F0, false},
    {0x00A09AEE, 8, 4, 0x04C9F8F4, false},
    {0x00A09B05, 8, 4, 0x04C9F8F8, false},
    {0x00A09B1C, 8, 4, 0x04C9F8FC, false},
    {0x00A09B33, 8, 4, 0x04C9F900, false},
    {0x00A09B78, 8, 4, 0x04C9ECA8, false},
    {0x00A0A29C, 8, 4, 0x04C9F8F0, false},
    {0x00A180C4, 8, 4, 0x04C9F914, false},
    {0x00A180D5, 7, 3, 0x04C9ECA8, false},
    {0x00A18128, 8, 4, 0x04C9EC90, false},
    {0x00A1813A, 7, 3, 0x04C9ECB8, false},
    {0x00A18155, 7, 3, 0x04C9ECB8, false},
    {0x00A18176, 8, 4, 0x04C9ECA8, false},
    {0x00A181AD, 8, 4, 0x04C9F8F0, false},
    {0x00A181EA, 8, 4, 0x04C9F914, false},
    {0x00A181F4, 8, 4, 0x04C9EC90, false},
    {0x00A18215, 8, 4, 0x04C9ECA4, false},
    {0x00A1821F, 8, 4, 0x04C9ECA0, false},
    {0x00A18230, 8, 4, 0x04C9EC9C, false},
    {0x00A18255, 8, 4, 0x04C9ECB0, false},
};

// Per-local-client registration list heads, stride 8, [2] on the PC. Accessor
// 0x02834F50 (&base[lc], walked by 0x023B4550 with the destructor at
// 0x02834EF0); count at 0x1A880478; objects 0x390 bytes keyed by byte [obj+2].
// Slot 2 (0x1A8804D0) is float data written by the movups at 0x02F6A932 and
// slot 3 (0x1A8804D8) is a live pointer global with 11 refs, so lc=2 read
// 0x3F3504F3 as a list head and faulted at 0x023B456D. [2] -> [4], zero-filled
// = a NULL head the walker exits on. 7 references: 6 rip-relative + 1 ABS32
inline constexpr reloc_ref lc_subscribers_refs[] = {
    {0x027BBD02, 7, 3, 0x1A801540, true},  {0x027BBD3B, 7, 3, 0x1A801540, true},
    {0x027BBDA4, 7, 3, 0x1A801540, true},  {0x027BBDE3, 7, 3, 0x1A801540, true},
    {0x02EEBDB2, 7, 3, 0x1A801540, true},  {0x02EEBDB9, 7, 3, 0x1A801548, true},
    {0x027AFC5C, 8, 4, 0x1A801540, false},
};

// DELAYED: s_gamePads - two 0x70-byte records on PC, expanded to four only
// after the first guest has created a real two-player lobby.  Activating this
// at startup reaches uninitialised gamepad state and crashes at 0x022E9550. 38
// references: 21 rip-relative + 17 ABS32
inline constexpr reloc_ref gamepads_refs[] = {
    {0x02284E23, 7, 3, 0x17DEF3E4, true},
    {0x02285169, 7, 3, 0x17DEF3E0, true},
    {0x02285413, 7, 3, 0x17DEF3E0, true},
    {0x02285473, 7, 3, 0x17DEF3E4, true},
    {0x022854E2, 7, 3, 0x17DEF400, true},
    {0x02285703, 7, 3, 0x17DEF3E0, true},
    {0x02285723, 7, 3, 0x17DEF3E0, true},
    {0x022857C3, 7, 3, 0x17DEF3E0, true},
    {0x0228584A, 7, 3, 0x17DEF3E0, true},
    {0x0228589A, 7, 3, 0x17DEF3E0, true},
    {0x02285971, 7, 3, 0x17DEF3E0, true},
    {0x02285B43, 7, 3, 0x17DEF434, true},
    {0x02285B73, 7, 3, 0x17DEF430, true},
    {0x02285D76, 7, 3, 0x17DEF400, true},
    {0x02285F5C, 7, 3, 0x17DEF3E0, true},
    {0x0228603A, 7, 3, 0x17DEF3E0, true},
    {0x022863FF, 7, 3, 0x17DEF3E4, true},
    {0x1B22A15B, 7, 3, 0x17DEF3E0, true},
    {0x1D55E11C, 7, 3, 0x17DEF438, true},
    {0x1B6843B0, 7, 3, 0x17DEF3E0, true},
    {0x1B4F936D, 7, 3, 0x17DEF3E4, true},
    {0x0228488A, 8, 4, 0x17DEF3E4, false},
    {0x022848A6, 8, 4, 0x17DEF3E4, false},
    {0x02284C55, 7, 3, 0x17DEF3E4, false},
    {0x02284D45, 7, 3, 0x17DEF3E4, false},
    {0x02284D9E, 7, 3, 0x17DEF3E4, false},
    {0x02284FCA, 7, 3, 0x17DEF3E4, false},
    {0x02285C80, 7, 3, 0x17DEF438, false},
    {0x02285C8F, 8, 4, 0x17DEF43A, false},
    {0x02285C9B, 8, 4, 0x17DEF3E0, false},
    {0x02285CA5, 8, 4, 0x17DEF3E4, false},
    {0x02286193, 7, 3, 0x17DEF438, false},
    {0x022861AC, 8, 4, 0x17DEF430, false},
    {0x022861B6, 8, 4, 0x17DEF434, false},
    {0x022861E2, 8, 4, 0x17DEF43A, false},
    {0x022861F0, 8, 4, 0x17DEF3E4, false},
    {0x1B31F0B4, 7, 3, 0x17DEF3E0, false},
    {0x1B31F0C8, 8, 4, 0x17DEF3E4, false},
};

inline constexpr reloc_table gamepads_reloc_table = {
    "gamepads", 0x17DEF3E0, 0xE0, 0x1C0, gamepads_refs, 38, nullptr, 0};

inline constexpr reloc_table reloc_tables[] = {
    {"bit_array", 0x04C98B80, 0xC0, 0x180, bit_array_refs, 32, nullptr, 0},
    {"storage", 0x1788EAC0, 0x112B0, 0x22560, storage_refs, 25, nullptr, 0},
    {"client_objs", 0x03390190, 0x10, 0x20, client_objs_refs, 19,
     client_objs_end_refs, 3},
    {"client_ui", 0x14F344B0, 0x2340, 0x45C0, client_ui_refs, 2, nullptr, 0},
    {"netchan", 0x16DEAEB0, 0x250, 0x4A0, netchan_refs, 15, nullptr, 0},
    {"objtab_a", 0x09B35878, 0x10, 0x20, objtab_a_refs, 28, nullptr, 0},
    {"objtab_b", 0x09931F00, 0x20, 0x40, objtab_b_refs, 3, nullptr, 0},
    {"fps_ctx", 0x04C98B70, 0x10, 0x10, fps_ctx_refs, 92, nullptr, 0},
    {"voice_comm", 0x0535BCB0, 0x1468, 0x28D0, voice_comm_refs, 12, nullptr, 0},
    {"cbuf", 0x1681EFB8, 0x20, 0x40, cbuf_refs, 4, nullptr, 0},
    {"players_kb", 0x052739F0, 0x930, 0x1260, players_kb_refs, 213, nullptr, 0},
    {"match_scoreboard", 0x04C9EC90, 0x1BD0, 0x37A0, match_scoreboard_refs, 70,
     nullptr, 0},
    {"lc_subscribers", 0x1A801540, 0x10, 0x20, lc_subscribers_refs, 7, nullptr,
     0},
};
} // namespace splitscreen
