name: Check Formatting

on: [push, pull_request]

jobs:
  formatting-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format style check
        uses: jidicula/actions-clang-format@v4.18.0
        check-path: "src"
